<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">EntryGetValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBF
bnRyeUdldFZhbHVlIEZsb3cKICoKICogamF2YS51dGlsLk1hcC5FbnRyeSBnZXRWYWx1ZSBtZXRo
b2QKICoKICogQ29weXJpZ2h0IChjKSAyMDExLCBTa3lyciBMdGQgKHd3dy5za3lyci5pcykuIEFs
bCByaWdodHMgcmVzZXJ2ZWQuCiAqCiAqIElucHV0OiAgRW50cnkgKGphdmEudXRpbC5NYXAuRW50
cnkpCiAqIE91dHB1dDogVmFsdWUgKGphdmEubGFuZy5PYmplY3QpCiAqCiAqIFJldmlzaW9uIEhp
c3RvcnkKICogMTEwMTIwIEdPUyAoZ2Vpcm11bmR1ckBza3lyci5pcykgQ3JlYXRlZAogKgogKiBV
bml0IHRlc3QKICogMTEwMTIwIEdPUyBGaW5pc2hlZAogKgogKi8KCi8vIEluaXRpYWxpemUKSURh
dGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJzb3IocGlwZWxpbmUpOwoKamF2YS51dGlsLk1h
cC5FbnRyeSBlbnRyeSA9IEV4dHJhY3RFbnRyeShpZGMsIGZhbHNlKTsKCmlmKGVudHJ5ICE9IG51
bGwpCnsKICBPYmplY3QgdmFsdWUgPSBlbnRyeS5nZXRWYWx1ZSgpOwogIGlmKHZhbHVlICE9IG51
bGwpCiAgICBJRGF0YVV0aWwucHV0KGlkYywgVkFMVUUsIHZhbHVlKTsKfQoKLy8gQ2xlYW4gdXAK
aWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgRW50cnlHZXRWYWx1ZSBGbG93
IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqLw==</value>
</Values>
