<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IDataUtil_getObjectArray_fromdoc_put_intopipe</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEg
RG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoIHBpcGVsaW5lQ3Vyc29yLCAiRG9jdW1lbnQi
ICk7CmlmICggRG9jdW1lbnQgIT0gbnVsbCkgewoJU3RyaW5nCUdldExhYmVsID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJHZXRMYWJlbCIgKTsKCUlEYXRhQ3Vyc29yIGRD
PURvY3VtZW50LmdldEN1cnNvcigpOwoJT2JqZWN0W10gb2JqZWN0ID0gSURhdGFVdGlsLmdldE9i
amVjdEFycmF5KCBkQywgR2V0TGFiZWwgKTsKCWRDLmRlc3Ryb3koKTsKCVN0cmluZwlQdXRMYWJl
bCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiUHV0TGFiZWwiICk7CglJ
RGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCBQdXRMYWJlbCwgb2JqZWN0KTsKfQpwaXBlbGlu
ZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
