<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">StringVectorAdd</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
dHJpbmdWZWN0b3JBZGQgRmxvdwogKi8KCi8vIENvbnN0YW50cwpmaW5hbCBTdHJpbmcgVmFyTmFt
ZVZhbHVlID0gIlZhbHVlIjsKZmluYWwgU3RyaW5nIFZhck5hbWVTdHJpbmdWZWN0b3IgPSAiU3Ry
aW5nVmVjdG9yIjsKCi8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CmlmKGlkYyA9PSBudWxsKQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJG
YWlsZWQgdG8gZ2V0IEN1cnNvciB0byBQaXBlbGluZSIpOwoKLy8gVHJ5IHRvIGdldCB0aGUgVmFs
dWUKU3RyaW5nIHZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhpZGMsIFZhck5hbWVWYWx1ZSk7
CmlmKHZhbHVlID09IG51bGwpCnsKICBpZGMuZGVzdHJveSgpOwogIHJldHVybjsKfQoKLy8gVHJ5
IHRvIGdldCB0aGUgU3RyaW5nIFZlY3RvcgpPYmplY3Qgc3RyaW5nVmVjdG9yT2JqZWN0ID0gSURh
dGFVdGlsLmdldChpZGMsIFZhck5hbWVTdHJpbmdWZWN0b3IpOwoKLy8gQ3JlYXRlIHRoZSBWZWN0
b3IgVmFyaWFibGVzCmphdmEudXRpbC5WZWN0b3IgdmVjdG9yOwoKaWYoc3RyaW5nVmVjdG9yT2Jq
ZWN0IGluc3RhbmNlb2YgamF2YS51dGlsLlZlY3RvcikKICB2ZWN0b3IgPSAoamF2YS51dGlsLlZl
Y3RvcilzdHJpbmdWZWN0b3JPYmplY3Q7CmVsc2UKICB2ZWN0b3IgPSBuZXcgamF2YS51dGlsLlZl
Y3RvcigpOwoKLy8gQWRkIHRoZSBzdHJpbmcKdmVjdG9yLmFkZCh2YWx1ZSk7CgpJRGF0YVV0aWwu
cHV0KGlkYywgVmFyTmFtZVN0cmluZ1ZlY3RvciwgdmVjdG9yKTsKCgovLyBDbGVhbiB1cAppZGMu
ZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBTdHJpbmdWZWN0b3JBZGQgRmxvdyBl
bmRzCiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKi8=</value>
</Values>
