<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">Get</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBH
ZXQgRmxvdwogKgogKiBqYXZhLnV0aWwuQ2FsZW5kYXIgZ2V0IG1ldGhvZAogKgogKiBDb3B5cmln
aHQgKGMpIDIwMTEsIFNreXJyIEx0ZCAod3d3LnNreXJyLmlzKS4gQWxsIHJpZ2h0cyByZXNlcnZl
ZC4KICoKICogSW5wdXQ6ICBDYWxlbmRhciAgIChqYXZhLnV0aWwuQ2FsZW5kYXIpCiAqICAgICAg
ICAgRmllbGQgICAgICAoU3RyaW5nKQogKgogKiBPdXRwdXQ6IFZhbHVlICAgICAgKFN0cmluZyAt
IEludGVnZXIpCiAqCiAqIFJldmlzaW9uIEhpc3RvcnkKICogMTExMDAzIEdPUyAoZ2Vpcm11bmR1
ckBza3lyci5pcykgQ3JlYXRlZAogKgogKiBVbml0IHRlc3QKICogMTExMDAzIEdPUyBGaW5pc2hl
ZAogKgogKi8KCi8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJz
b3IocGlwZWxpbmUpOwoKLy8gRXh0cmFjdCBQYXJhbWV0ZXJzCmphdmEudXRpbC5DYWxlbmRhciBj
YWwgPSBFeHRyYWN0Q2FsZW5kYXIoaWRjLCBmYWxzZSk7CmludCBmaWVsZCA9IEV4dHJhY3RGaWVs
ZChpZGMsIGZhbHNlKTsKCmlmKGNhbCAhPSBudWxsICYmIGZpZWxkID49IDApCiAgSURhdGFVdGls
LnB1dChpZGMsIFZBTFVFLCBJbnRlZ2VyLnRvU3RyaW5nKGNhbC5nZXQoZmllbGQpKSk7CgovLyBD
bGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBHZXQgRmxvdyBl
bmRzCiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKi8K</value>
</Values>
