<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">localinvoke_dangerous</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCi8vSURh
dGFDdXJzb3IgdG1wY3VycyA9IHRtcC5nZXRDdXJzb3IoKTsKU3RyaW5nIHNlcnZpY2UgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIiRzZXJ2aWNlIiApOwpTdHJpbmcgZm9s
ZGVyID0gc2VydmljZS5zcGxpdCgiOiIpWzBdOwpTdHJpbmcgbmFtZSA9IHNlcnZpY2Uuc3BsaXQo
IjoiKVsxXTsKLy9JRGF0YSBwaXBlID0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBlbGluZUN1cnNv
ciwgInBpcGVsaW5lIik7CnRyeSB7CglTZXJ2aWNlLmRvSW52b2tlKGZvbGRlciwgbmFtZSwgcGlw
ZWxpbmUpOwp9ICBjYXRjaChFeGNlcHRpb24gZSkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oZSk7Cn0KCg==</value>
</Values>
