<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">EntryGetKey</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBF
bnRyeUdldEtleSBGbG93CiAqCiAqIGphdmEudXRpbC5NYXAuRW50cnkgZ2V0S2V5IG1ldGhvZAog
KgogKiBDb3B5cmlnaHQgKGMpIDIwMTEsIFNreXJyIEx0ZCAod3d3LnNreXJyLmlzKS4gQWxsIHJp
Z2h0cyByZXNlcnZlZC4KICoKICogSW5wdXQ6ICBFbnRyeSAoamF2YS51dGlsLk1hcC5FbnRyeSkK
ICogT3V0cHV0OiBLZXkgICAoamF2YS5sYW5nLk9iamVjdCkKICoKICogUmV2aXNpb24gSGlzdG9y
eQogKiAxMTAxMjAgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQg
dGVzdAogKiAxMTAxMjAgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1
cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0aWwuTWFwLkVu
dHJ5IGVudHJ5ID0gRXh0cmFjdEVudHJ5KGlkYywgZmFsc2UpOwoKaWYoZW50cnkgIT0gbnVsbCkK
ewogIE9iamVjdCBrZXkgPSBlbnRyeS5nZXRLZXkoKTsKICBpZihrZXkgIT0gbnVsbCkKICAgIElE
YXRhVXRpbC5wdXQoaWRjLCBLRVksIGtleSk7Cn0KCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7
CgovKgogKiBXZWIgTWV0aG9kcyBKYXZhIEVudHJ5R2V0S2V5IEZsb3cgZW5kcwogKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKiovCg==</value>
</Values>
