<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">filterDocumentList</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBm
aWx0ZXJEb2N1bWVudExpc3QgRmxvdwogKi8KICAgIAovLyBDb25zdGFudHMKZmluYWwgU3RyaW5n
IFZhck5hbWVJbkxpc3QgPSAiSW5MaXN0IjsKZmluYWwgU3RyaW5nIFZhck5hbWVPdXRMaXN0ID0g
Ik91dExpc3QiOwpmaW5hbCBTdHJpbmcgVmFyTmFtZUZpbHRlciA9ICJGaWx0ZXIiOwpmaW5hbCBT
dHJpbmcgVmFyTmFtZUtleSA9ICJLZXkiOwogICAgCi8vIEluaXRpYWxpemUgcGlwZWxpbmUgY3Vy
c29yCklEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKLy8gVHJ5IHRvIGdl
dCB0aGUgaW5wdXQKSURhdGFbXSBpbmxpc3QgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShpZGMs
IFZhck5hbWVJbkxpc3QpOwpTdHJpbmdbXSBmaWx0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nQXJy
YXkoaWRjLCBWYXJOYW1lRmlsdGVyKTsKU3RyaW5nIGtleSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
aWRjLCBWYXJOYW1lS2V5KTsKCi8vIENoZWNrIGlucHV0IGZvciBudWxsIG9yIGVtcHR5IGxpc3Rz
CmlmKGlubGlzdCA9PSBudWxsIHx8IGZpbHRlciA9PSBudWxsIHx8IGlubGlzdC5sZW5ndGggPT0g
MCB8fCBmaWx0ZXIubGVuZ3RoID09IDApCnsKICBpZGMuZGVzdHJveSgpOwogIHJldHVybjsKfQoK
Ly8gQ2hlY2sga2V5IGlucHV0IGZvciBudWxsIG9yIGVtcHR5IHN0cmluZwppZihrZXkgPT0gbnVs
bCB8fCBrZXkubGVuZ3RoKCkgPT0gMCkKewogIGlkYy5kZXN0cm95KCk7CiAgdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oIktleSBpcyBtaXNzaW5nIG9yIGVtcHR5IHN0cmluZyIpOwp9CgovLyBD
b252ZXJ0IGZpbHRlciB0byBsaXN0CmphdmEudXRpbC5BcnJheUxpc3QgZmlsdGVybGlzdCA9IG5l
dyBqYXZhLnV0aWwuQXJyYXlMaXN0KCk7CmZvcihpbnQgbiA9IGZpbHRlci5sZW5ndGggLSAxOyBu
ID49IDA7IG4tLSkKICBmaWx0ZXJsaXN0LmFkZChmaWx0ZXJbbl0pOwoKLy8gQ3JlYXRlIHRoZSBv
dXRwdXQgYXJyYXkKamF2YS51dGlsLkFycmF5TGlzdCBvdXRhcnJheSA9IG5ldyBqYXZhLnV0aWwu
QXJyYXlMaXN0KCk7CgovLyBXYWxrIHRoZSBJbiBMaXN0CmludCBsZW5ndGggPSBpbmxpc3QubGVu
Z3RoOwpmb3IoaW50IGkgPSAwOyBpIDwgbGVuZ3RoOyBpKyspCnsKICAvLyBTa2lwIGl0ZW0gaWYg
aXQgaXMgbnVsbAogIGlmKGlubGlzdFtpXSA9PSBudWxsKSBjb250aW51ZTsKICBJRGF0YUN1cnNv
ciBpdGVtID0gaW5saXN0W2ldLmdldEN1cnNvcigpOwogIGlmKGZpbHRlcmxpc3QuY29udGFpbnMo
SURhdGFVdGlsLmdldFN0cmluZyhpdGVtLCBrZXkpKSkKICAgIG91dGFycmF5LmFkZChpbmxpc3Rb
aV0pOwogIGl0ZW0uZGVzdHJveSgpOyAvLyBDbGVhbiB1cCBpdGVtCn0KCi8vIElmIG91dHB1dCBh
cnJheSBpcyBub3QgZW1wdHkgYWRkIHRoZSBhcnJheSB0byB0aGUgcGlwZWxpbmUKaWYoIW91dGFy
cmF5LmlzRW1wdHkoKSkKewogIElEYXRhW10gb3V0bGlzdCA9IG5ldyBJRGF0YVtvdXRhcnJheS5z
aXplKCldOwogIG91dGFycmF5LnRvQXJyYXkob3V0bGlzdCk7CiAgSURhdGFVdGlsLnB1dChpZGMs
IFZhck5hbWVPdXRMaXN0LCBvdXRsaXN0KTsKfQogICAgICAgIAovLyBDbGVhbiB1cAppZGMuZGVz
dHJveSgpOwogICAgCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgZmlsdGVyRG9jdW1lbnRMaXN0IEZs
b3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKiov</value>
</Values>
