<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">documentsToList</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEg
cGlwZSA9IElEYXRhVXRpbC5nZXRJRGF0YShwaXBlbGluZUN1cnNvciwicGlwZWxpbmUiKTsKaWYg
KHBpcGUgIT0gbnVsbCApIHsKCUlEYXRhQ3Vyc29yIHBDdXJzb3IgPSBwaXBlLmdldEN1cnNvcigp
OwoJamF2YS51dGlsLkFycmF5TGlzdCBhbERvY3MgPSBuZXcgamF2YS51dGlsLkFycmF5TGlzdCgp
OwoKCXdoaWxlKHBDdXJzb3IubmV4dCgpKSB7CgkJaWYocEN1cnNvci5nZXRWYWx1ZSgpIGluc3Rh
bmNlb2YgSURhdGEpCXsKCQkJYWxEb2NzLmFkZChwQ3Vyc29yLmdldFZhbHVlKCkpOwoJCX0KCX0K
CglpZiAoYWxEb2NzLnNpemUoKSA+IDApIHsKCQlJRGF0YVtdCWRvY3VtZW50cyA9IChJRGF0YVtd
KWFsRG9jcy50b0FycmF5KG5ldyBJRGF0YVthbERvY3Muc2l6ZSgpXSk7CgkJSURhdGFVdGlsLnB1
dCggcGlwZWxpbmVDdXJzb3IsICJkb2N1bWVudHMiLCBkb2N1bWVudHMgKTsKCX0KCXBDdXJzb3Iu
ZGVzdHJveSgpOwp9CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCg==</value>
</Values>
