<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">formattedNumber2number</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
CXN0ckZvcm1hdHRlZE51bWJlciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAiZm9ybWF0dGVkTnVtYmVyIiApOwpTdHJpbmcJc3RyTG9jYWxlID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJsb2NhbGUiICk7CgppZihzdHJGb3JtYXR0ZWROdW1iZXI9
PW51bGwgfHwgc3RyRm9ybWF0dGVkTnVtYmVyLnRyaW0oKS5lcXVhbHMoIiIpKQp7CglyZXR1cm47
Cn0KCnRyeQp7CglqYXZhLnRleHQuTnVtYmVyRm9ybWF0IG5mRm9ybWF0dGVyID0gamF2YS50ZXh0
Lk51bWJlckZvcm1hdC5nZXRJbnN0YW5jZSggbmV3IGphdmEudXRpbC5Mb2NhbGUoc3RyTG9jYWxl
KSk7CglOdW1iZXIgbk51bWJlcj0gbmZGb3JtYXR0ZXIucGFyc2Uoc3RyRm9ybWF0dGVkTnVtYmVy
KTsKCWRvdWJsZSBkVW5mb3JtYXR0ZWQgPSBuTnVtYmVyLmRvdWJsZVZhbHVlKCk7CglJRGF0YVV0
aWwucHV0KCBwaXBlbGluZUN1cnNvciwgIm51bWJlciIsIGRVbmZvcm1hdHRlZCsiIiApOwp9CmNh
dGNoKEV4Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3Nh
Z2UoKSk7Cn0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwo=</value>
</Values>
