<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">oneNode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFVdGlsLnB1dChwaXBlbGluZS5nZXRDdXJzb3IoKSwgIkNvdW50IiwgIiIrKChjb20ud20u
bGFuZy5mbG93LkZsb3dFbGVtZW50KUlEYXRhVXRpbC5nZXQocGlwZWxpbmUuZ2V0Q3Vyc29yKCks
ICJub2RlIikpLmdldE5vZGVDb3VudCgpICk7CklEYXRhVXRpbC5wdXQocGlwZWxpbmUuZ2V0Q3Vy
c29yKCksICJJbmRleCIsICIiKygoY29tLndtLmxhbmcuZmxvdy5GbG93RWxlbWVudClJRGF0YVV0
aWwuZ2V0KHBpcGVsaW5lLmdldEN1cnNvcigpLCAibm9kZSIpKS5nZXROb2RlSW5kZXgoKSApOwpJ
RGF0YVV0aWwucHV0KHBpcGVsaW5lLmdldEN1cnNvcigpLCAiRGlzcGxheVR5cGUiLCAiIisoKGNv
bS53bS5sYW5nLmZsb3cuRmxvd0VsZW1lbnQpSURhdGFVdGlsLmdldChwaXBlbGluZS5nZXRDdXJz
b3IoKSwgIm5vZGUiKSkuZ2V0RGlzcGxheVR5cGUoKSApOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5l
LmdldEN1cnNvcigpLCAiRW5hYmxlZCIsICIiKygoY29tLndtLmxhbmcuZmxvdy5GbG93RWxlbWVu
dClJRGF0YVV0aWwuZ2V0KHBpcGVsaW5lLmdldEN1cnNvcigpLCAibm9kZSIpKS5pc0VuYWJsZWQo
KSApOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5lLmdldEN1cnNvcigpLCAiaGFzTm9kZXMiLCAiIiso
KGNvbS53bS5sYW5nLmZsb3cuRmxvd0VsZW1lbnQpSURhdGFVdGlsLmdldChwaXBlbGluZS5nZXRD
dXJzb3IoKSwgIm5vZGUiKSkuaGFzTm9kZXMoKSApOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5lLmdl
dEN1cnNvcigpLCAiUGF0aCIsICIiKygoY29tLndtLmxhbmcuZmxvdy5GbG93RWxlbWVudClJRGF0
YVV0aWwuZ2V0KHBpcGVsaW5lLmdldEN1cnNvcigpLCAibm9kZSIpKS5nZXRQYXRoKCkgKTsKSURh
dGFVdGlsLnB1dChwaXBlbGluZS5nZXRDdXJzb3IoKSwgImdldE5vZGVzIiwgKChjb20ud20ubGFu
Zy5mbG93LkZsb3dFbGVtZW50KUlEYXRhVXRpbC5nZXQocGlwZWxpbmUuZ2V0Q3Vyc29yKCksICJu
b2RlIikpLmdldE5vZGVzKCkgKTs=</value>
</Values>
