<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IteratorNext</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBJ
dGVyYXRvck5leHQgRmxvdwogKgogKiBqYXZhLnV0aWwuSXRlcmF0b3IgbmV4dCBtZXRob2QKICoK
ICogQ29weXJpZ2h0IFx1MDBBOSAyMDA5LCBLXHUwMEY2Z3VuIEx0ZCAod3d3LmtvZ3VuLmlzKS4g
QWxsIHJpZ2h0cyByZXNlcnZlZC4KICoKICogSW5wdXQ6IGphdmEudXRpbC5JdGVyYXRvciBJdGVy
YXRvcgogKiBPdXRwdXQ6IE9iamVjdCBOZXh0CiAqCiAqIFJldmlzaW9uIEhpc3RvcnkKICogMDkw
MzE5IEdPUyAoZ2Vpcm11bmR1ckBrb2d1bi5pcykgQ3JlYXRlZAogKgogKiBVbml0IHRlc3QKICog
MDkwMzE5IEdPUyBub3QgZmluaXNoZWQKICoKICovCgovLyBJbml0aWFsaXplCklEYXRhQ3Vyc29y
IGlkYyA9IEdldEFuZENoZWNrQ3Vyc29yKHBpcGVsaW5lKTsKamF2YS51dGlsLkl0ZXJhdG9yIGl0
ID0gRXh0cmFjdEl0ZXJhdG9yKGlkYywgZmFsc2UpOwoKT2JqZWN0IHJlc3VsdCA9IG51bGw7Cmlm
KGl0ICE9IG51bGwpCiAgcmVzdWx0ID0gaXQubmV4dCgpOwoKLy8gQWRkIHRoZSByZXN1bHQgdG8g
dGhlIHBpcGVsaW5lCmlmKHJlc3VsdCAhPSBudWxsKQogIElEYXRhVXRpbC5wdXQoaWRjLCBORVhU
LCByZXN1bHQpOwoKLy8gQ2xlYW4gdXAKaWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2Rz
IEphdmEgSXRlcmF0b3JOZXh0IEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
