<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isArray</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKT2JqZWN0
IG9iamVjdD0gKChPYmplY3QpIElEYXRhVXRpbC5nZXQoIHBpcGVsaW5lQ3Vyc29yLCAib2JqZWN0
IiApICk7CmlmIChvYmplY3QgPT0gbnVsbCkgewoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJz
b3IsICJpc0FycmF5IiwgImZhbHNlIiApOwp9IGVsc2Ugewpib29sZWFuIGIgPSBvYmplY3QuZ2V0
Q2xhc3MoKS5pc0FycmF5KCk7CmlmIChiKSB7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
ciwgImlzQXJyYXkiLCAidHJ1ZSIgKTsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAi
b2JqZWN0bGlzdCIsIG9iamVjdCApOwoJSURhdGFVdGlsLnB1dFN0cmluZ0xpc3QoIHBpcGVsaW5l
Q3Vyc29yLCAib2JqZWN0bGlzdCIsIG9iamVjdCApOwp9IGVsc2UgewoJSURhdGFVdGlsLnB1dCgg
cGlwZWxpbmVDdXJzb3IsICJpc0FycmF5IiwgImZhbHNlIiApOwp9Cn0KcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw==</value>
</Values>
