<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">StringVectorContains</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
dHJpbmdWZWN0b3JDb250YWlucyBGbG93CiAqLwoKLy8gQ29uc3RhbnRzCmZpbmFsIFN0cmluZyBW
YXJOYW1lVmFsdWUgPSAiVmFsdWUiOwpmaW5hbCBTdHJpbmcgVmFyTmFtZVN0cmluZ1ZlY3RvciA9
ICJTdHJpbmdWZWN0b3IiOwpmaW5hbCBTdHJpbmcgVmFyTmFtZVN0cmluZ1ZlY3RvckNvbnRhaW5z
ID0gIlN0cmluZ1ZlY3RvckNvbnRhaW5zIjsKCi8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRj
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CmlmKGlkYyA9PSBudWxsKQogIHRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKCJGYWlsZWQgdG8gZ2V0IEN1cnNvciB0byBQaXBlbGluZSIpOwoKLy8gVHJ5
IHRvIGdldCB0aGUgVmFsdWUKU3RyaW5nIHZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhpZGMs
IFZhck5hbWVWYWx1ZSk7CgovLyBUcnkgdG8gZ2V0IHRoZSBTdHJpbmcgVmVjdG9yCk9iamVjdCBz
dHJpbmdWZWN0b3JPYmplY3QgPSBJRGF0YVV0aWwuZ2V0KGlkYywgVmFyTmFtZVN0cmluZ1ZlY3Rv
cik7CgovLyBDcmVhdGUgdGhlIENvbnRhaW5zIFZhcmlhYmxlcwpib29sZWFuIGNvbnRhaW5zID0g
ZmFsc2U7CgppZihzdHJpbmdWZWN0b3JPYmplY3QgaW5zdGFuY2VvZiBqYXZhLnV0aWwuVmVjdG9y
KQogIGNvbnRhaW5zID0gKChqYXZhLnV0aWwuVmVjdG9yKXN0cmluZ1ZlY3Rvck9iamVjdCkuY29u
dGFpbnModmFsdWUpOwoKSURhdGFVdGlsLnB1dAogICAgICAgICgKICAgICAgICBpZGMsIAogICAg
ICAgIFZhck5hbWVTdHJpbmdWZWN0b3JDb250YWlucywgCiAgICAgICAgQm9vbGVhbi50b1N0cmlu
Zyhjb250YWlucykudG9Mb3dlckNhc2UoKQogICAgICAgICk7CgovLyBDbGVhbiB1cAppZGMuZGVz
dHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBTdHJpbmdWZWN0b3JDb250YWlucyBGbG93
IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqLw==</value>
</Values>
