<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">SetContains</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
ZXRDb250YWlucyBGbG93CiAqCiAqIGphdmEudXRpbC5TZXQgY29udGFpbnMgbWV0aG9kCiAqCiAq
IENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRz
IHJlc2VydmVkLgogKgogKiBJbnB1dDogIFNldCAgICAgIChqYXZhLnV0aWwuU2V0KQogKiAgICAg
ICAgIE9iamVjdCAgIChqYXZhLmxhbmcuT2JqZWN0KQogKiAgICAgICAgIFN0cmluZyAgIChTdHJp
bmcpCiAqIE91dHB1dDogQ29udGFpbnMgKFN0cmluZyBmcm9tIGJvb2xlYW4pCiAqCiAqIFJldmlz
aW9uIEhpc3RvcnkKICogMTEwMTE4IEdPUyAoZ2Vpcm11bmR1ckBza3lyci5pcykgQ3JlYXRlZAog
KgogKiBVbml0IHRlc3QKICogMTEwMTE4IEdPUyBGaW5pc2hlZAogKgogKi8KCi8vIEluaXRpYWxp
emUKSURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJzb3IocGlwZWxpbmUpOwoKamF2YS51
dGlsLlNldCBzZXQgPSBFeHRyYWN0U2V0KGlkYywgZmFsc2UpOwpqYXZhLmxhbmcuT2JqZWN0IG9i
aiA9IEV4dHJhY3RPYmplY3QoaWRjKTsKamF2YS5sYW5nLlN0cmluZyBzdHIgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKGlkYywgU1RSSU5HKTsKCmJvb2xlYW4gcmVzdWx0ID0gZmFsc2U7CgppZihzZXQg
IT0gbnVsbCkKewogIGlmKHN0ciAhPSBudWxsKQogICAgcmVzdWx0ID0gc2V0LmNvbnRhaW5zKHN0
cik7CiAgZWxzZQogICAgcmVzdWx0ID0gc2V0LmNvbnRhaW5zKG9iaik7Cn0KCmlmKHJlc3VsdCkK
ICBJRGF0YVV0aWwucHV0KGlkYywgQ09OVEFJTlMsIEJvb2xlYW4udG9TdHJpbmcocmVzdWx0KS50
b0xvd2VyQ2FzZSgpKTsKCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7CgovKgogKiBXZWIgTWV0
aG9kcyBKYXZhIFNldENvbnRhaW5zIEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
