<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MatcherAppendReplacement</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXRjaGVyQXBwZW5kUmVwbGFjZW1lbnQgRmxvdwogKgogKiBqYXZhLnV0aWwucmVnZXguTWF0Y2hl
ciBhcHBlbmRSZXBsYWNlbWVudCBtZXRob2QKICoKICogQ29weXJpZ2h0IChjKSAyMDExLCBTa3ly
ciBMdGQgKHd3dy5za3lyci5pcykuIEFsbCByaWdodHMgcmVzZXJ2ZWQuCiAqCiAqIElucHV0OiAg
TWF0Y2hlciAgICAgIChqYXZhLnV0aWwucmVnZXguTWF0Y2hlcikKICogICAgICAgICBTdHJpbmdC
dWZmZXIgKGphdmEubGFuZy5TdHJpbmdCdWZmZXIpCiAqICAgICAgICAgUmVwbGFjZW1lbnQgIChT
dHJpbmcgLSBvcHRpb25hbCkKICoKICogT3V0cHV0OiBNYXRjaGVyICAgICAgKGphdmEudXRpbC5y
ZWdleC5NYXRjaGVyKQogKgogKiBSZXZpc2lvbiBIaXN0b3J5CiAqIDExMDkxMCBHT1MgKGdlaXJt
dW5kdXJAc2t5cnIuaXMpIENyZWF0ZWQKICoKICogVW5pdCB0ZXN0CiAqIDExMDkxMCBHT1MgRmlu
aXNoZWQKICoKICovCiAgICAKLy8gQ29uc3RhbnRzCmZpbmFsIFN0cmluZyBWYXJOYW1lUmVwbGFj
ZW1lbnQgPSAiUmVwbGFjZW1lbnQiOwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBH
ZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0aWwucmVnZXguTWF0Y2hlciBtYXRj
aGVyID0gRXh0cmFjdE1hdGNoZXIoaWRjLCBmYWxzZSk7CmphdmEubGFuZy5TdHJpbmdCdWZmZXIg
c3RyaW5nQnVmZmVyID0gRXh0cmFjdFN0cmluZ0J1ZmZlcihpZGMsIHRydWUpOwpTdHJpbmcgcmVw
bGFjZW1lbnQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgVmFyTmFtZVJlcGxhY2VtZW50KTsK
CmlmKG1hdGNoZXIgIT0gbnVsbCkKICBJRGF0YVV0aWwucHV0CiAgICAgICAgICAoaWRjLCBNQVRD
SEVSLCBtYXRjaGVyLmFwcGVuZFJlcGxhY2VtZW50KHN0cmluZ0J1ZmZlciwgcmVwbGFjZW1lbnQp
KTsKCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7CgovKgogKiBXZWIgTWV0aG9kcyBKYXZhIE1h
dGNoZXJBcHBlbmRSZXBsYWNlbWVudCBGbG93IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqLwo=</value>
</Values>
