<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IDataUtil_get_fromdoc_put_intopipe</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEg
RG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoIHBpcGVsaW5lQ3Vyc29yLCAiRG9jdW1lbnQi
ICk7CmlmICggRG9jdW1lbnQgIT0gbnVsbCkgewoJU3RyaW5nCUdldExhYmVsID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJHZXRMYWJlbCIgKTsKCUlEYXRhQ3Vyc29yIGRD
PURvY3VtZW50LmdldEN1cnNvcigpOwoJT2JqZWN0CW9iamVjdCA9IElEYXRhVXRpbC5nZXQoIGRD
LCBHZXRMYWJlbCApOwoJZEMuZGVzdHJveSgpOwoJU3RyaW5nCVB1dExhYmVsID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJQdXRMYWJlbCIgKTsKCUlEYXRhVXRpbC5wdXQo
cGlwZWxpbmVDdXJzb3IsIFB1dExhYmVsLCBvYmplY3QpOwp9CnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTs=</value>
</Values>
