<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">CreateStringBuffer</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBD
cmVhdGVTdHJpbmdCdWZmZXIgRmxvdwogKgogKiBqYXZhLmxhbmcuU3RyaW5nQnVmZmVyIENvbnN0
cnVjdG9ycwogKgogKiBDb3B5cmlnaHQgKGMpIDIwMTEsIFNreXJyIEx0ZCAod3d3LnNreXJyLmlz
KS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4KICoKICogSW5wdXQ6ICBMZW5ndGggKFN0cmluZyAtIG9w
dGlvbmFsIGludGVnZXIpCiAqICAgICAgICAgU3RyICAgIChTdHJpbmcgLSBvcHRpb25hbCkKICoK
ICogT3V0cHV0OiBTdHJpbmdCdWZmZXIgKGphdmEubGFuZy5TdHJpbmdCdWZmZXIpCiAqCiAqIFJl
dmlzaW9uIEhpc3RvcnkKICogMTEwOTEwIEdPUyAoZ2Vpcm11bmR1ckBza3lyci5pcykgQ3JlYXRl
ZAogKgogKiBVbml0IHRlc3QKICogMTEwOTEwIEdPUyBGaW5pc2hlZAogKgogKi8KCi8vIENvbnN0
YW50cwpmaW5hbCBTdHJpbmcgVmFyTmFtZUxlbmd0aCA9ICJMZW5ndGgiOwpmaW5hbCBTdHJpbmcg
VmFyTmFtZVN0ciA9ICJTdHIiOwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBHZXRB
bmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpTdHJpbmcgc3RyID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhpZGMsIFZhck5hbWVTdHIpOwpJbnRlZ2VyIGxlbmd0aCA9IEV4dHJhY3RJbnRlZ2VyKGlkYywg
VmFyTmFtZUxlbmd0aCwgZmFsc2UpOwoKaWYoc3RyID09IG51bGwgJiYgbGVuZ3RoID09IG51bGwp
CiAgSURhdGFVdGlsLnB1dAogICAgICAgICAgKGlkYywgU1RSSU5HX0JVRkZFUiwgbmV3IGphdmEu
bGFuZy5TdHJpbmdCdWZmZXIoKSk7CmVsc2UgaWYgKHN0ciAhPSBudWxsKQogIElEYXRhVXRpbC5w
dXQKICAgICAgICAgIChpZGMsIFNUUklOR19CVUZGRVIsIG5ldyBqYXZhLmxhbmcuU3RyaW5nQnVm
ZmVyKHN0cikpOwplbHNlIGlmIChsZW5ndGggIT0gbnVsbCkKICBJRGF0YVV0aWwucHV0CiAgICAg
ICAgICAoaWRjLCBTVFJJTkdfQlVGRkVSLCBuZXcgamF2YS5sYW5nLlN0cmluZ0J1ZmZlcihsZW5n
dGguaW50VmFsdWUoKSkpOwoKLy8gQ2xlYW4gdXAKaWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBN
ZXRob2RzIEphdmEgQ3JlYXRlU3RyaW5nQnVmZmVyIEZsb3cgZW5kcwogKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KiovCg==</value>
</Values>
