<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ListIterator</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBM
aXN0SXRlcmF0b3IgRmxvdwogKgogKiBqYXZhLnV0aWwuTGlzdCBpdGVyYXRvciBtZXRob2QKICoK
ICogQ29weXJpZ2h0IFx1MDBBOSAyMDA5LCBLXHUwMEY2Z3VuIEx0ZCAod3d3LmtvZ3VuLmlzKS4g
QWxsIHJpZ2h0cyByZXNlcnZlZC4KICoKICogSW5wdXQ6IGphdmEudXRpbC5MaXN0IExpc3QKICog
T3V0cHV0OiBqYXZhLnV0aWwuSXRlcmF0b3IgSXRlcmF0b3IKICoKICogUmV2aXNpb24gSGlzdG9y
eQogKiAwOTAzMTYgR09TIChnZWlybXVuZHVyQGtvZ3VuLmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQg
dGVzdAogKiAwOTAzMTYgR09TIG5vdCBmaW5pc2hlZAogKgogKi8KCi8vIEluaXRpYWxpemUKSURh
dGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJzb3IocGlwZWxpbmUpOwoKamF2YS51dGlsLkxp
c3QgbGlzdCA9IEV4dHJhY3RMaXN0KGlkYyk7CgppZihsaXN0ICE9IG51bGwpCnsKICBqYXZhLnV0
aWwuSXRlcmF0b3IgaXRlcmF0b3IgPSBsaXN0Lml0ZXJhdG9yKCk7CiAgSURhdGFVdGlsLnB1dChp
ZGMsIElURVJBVE9SLCBpdGVyYXRvcik7Cn0KCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7Cgov
KgogKiBXZWIgTWV0aG9kcyBKYXZhIExpc3RJdGVyYXRvciBGbG93IGVuZHMKICoqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqLwo=</value>
</Values>
