<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">StreamToPipeline</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IAogIHsKICAgIElEYXRhVXRpbCBzcl91dGlsID0gbmV3IElEYXRhVXRpbCgpOyAKICAgIElE
YXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CiAgICBwaXBl
bGluZUN1cnNvci5maXJzdCgic3Jfc3RyZWFtIik7CiAgICBJbnB1dFN0cmVhbSBzcl9zdHJlYW0g
PSAoSW5wdXRTdHJlYW0pICBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwogICAgSURhdGFYTUxD
b2RlciBzcl9JRGF0YVhNTENvZGVyID0gbmV3IElEYXRhWE1MQ29kZXIoKTsKICAgIElEYXRhIHNy
X0lEYXRhID0gc3JfSURhdGFYTUxDb2Rlci5kZWNvZGUoc3Jfc3RyZWFtKTsKICAgIHNyX3V0aWwu
bWVyZ2Uoc3JfSURhdGEscGlwZWxpbmUpOwogIH0gIApjYXRjaChFeGNlcHRpb24gZSkgCiAgewog
ICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7CiAgfQ==</value>
</Values>
