<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">CreateArrayList</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBB
cnJheUxpc3QgRmxvdwogKgogKiBDcmVhdGUgbmV3IGphdmEudXRpbC5WZWN0b3IKICoKICogQ29w
eXJpZ2h0IChjKSAyMDExLCBTa3lyciBMdGQgKHd3dy5za3lyci5pcykuIEFsbCByaWdodHMgcmVz
ZXJ2ZWQuCiAqCiAqIE91dHB1dDogTmV3IEFycmF5TGlzdCBvYmplY3QKICoKICogUmV2aXNpb24g
SGlzdG9yeQogKiAxMTAxMTggR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAq
IFVuaXQgdGVzdAogKiAxMTAxMTggR09TIG5vdCBmaW5pc2hlZAogKgogKi8KCi8vIENvbnN0YW50
cwpmaW5hbCBTdHJpbmcgVmFyTmFtZUFycmF5TGlzdCA9ICJBcnJheUxpc3QiOwoKLy8gSW5pdGlh
bGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgovLyBB
ZGQgdGhlIHJlc3VsdCB0byB0aGUgcGlwZWxpbmUKSURhdGFVdGlsLnB1dChpZGMsIFZhck5hbWVB
cnJheUxpc3QsIG5ldyBqYXZhLnV0aWwuQXJyYXlMaXN0KCkpOwoKLy8gQ2xlYW4gdXAKaWRjLmRl
c3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgQ3JlYXRlQXJyYXlMaXN0IEZsb3cgZW5k
cwogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
