<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">SetTime</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
ZXRUaW1lIEZsb3cKICoKICogamF2YS51dGlsLkNhbGVuZGFyIHNldFRpbWUgbWV0aG9kCiAqCiAq
IENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRz
IHJlc2VydmVkLgogKgogKiBJbnB1dDogIENhbGVuZGFyICAgKGphdmEudXRpbC5DYWxlbmRhcikK
ICogICAgICAgICBEYXRlICAgICAgIChqYXZhLnV0aWwuRGF0ZSkKICoKICogUmV2aXNpb24gSGlz
dG9yeQogKiAxMTEwMDMgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVu
aXQgdGVzdAogKiAxMTEwMDMgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJRGF0
YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0aWwuQ2Fs
ZW5kYXIgY2FsID0gRXh0cmFjdENhbGVuZGFyKGlkYywgdHJ1ZSk7Ck9iamVjdCBvYmogPSBJRGF0
YVV0aWwuZ2V0KGlkYywgREFURSk7CgppZihvYmogPT0gbnVsbCkKICB0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbigiVGhlIERhdGUgcGFyYW1ldGVyIGlzIHVuZGVmaW5lZCIpOwppZighKG9iaiBp
bnN0YW5jZW9mIGphdmEudXRpbC5EYXRlKSkKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
VGhlIERhdGUgcGFyYW1ldGVyIGlzIG5vdCBhbiBpbnN0YW5jZSBvZiBEYXRlIik7CgpqYXZhLnV0
aWwuRGF0ZSBkYXRlID0gKGphdmEudXRpbC5EYXRlKW9iajsKCmNhbC5zZXRUaW1lKGRhdGUpOwoK
Ly8gQ2xlYW4gdXAKaWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgU2V0VGlt
ZSBGbG93IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqLwo=</value>
</Values>
