<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ListAdd</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBM
aXN0QWRkIEZsb3cKICoKICogamF2YS51dGlsLkxpc3QgYWRkIG1ldGhvZAogKgogKiBDb3B5cmln
aHQgXHUwMEE5IDIwMDksIEtcdTAwRjZndW4gTHRkICh3d3cua29ndW4uaXMpLiBBbGwgcmlnaHRz
IHJlc2VydmVkLgogKgogKiBJbnB1dDoKICogICBqYXZhLnV0aWwuTGlzdCBMaXN0CiAqICAgT2Jq
ZWN0ICAgICAgICAgVmFsdWUKICogICBTdHJpbmcgICAgICAgICBWYWx1ZVN0cmluZwogKgogKiBS
ZXZpc2lvbiBIaXN0b3J5CiAqIDA5MDMxNiBHT1MgKGdlaXJtdW5kdXJAa29ndW4uaXMpIENyZWF0
ZWQKICogMTEwNTA5IEdPUyBBZGQgc3VwcG9ydCBmb3IgU3RyaW5nIFZhbHVlCiAqCiAqIFVuaXQg
dGVzdAogKiAxMTA1MDkgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1
cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0aWwuTGlzdCBs
aXN0ID0gRXh0cmFjdExpc3QoaWRjKTsKCk9iamVjdCBvYmpWYWx1ZSA9IElEYXRhVXRpbC5nZXQo
aWRjLCBWQUxVRSk7ClN0cmluZyBzdHJWYWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjLCBW
QUxVRV9TVFJJTkcpOwoKaWYob2JqVmFsdWUgIT0gbnVsbCkKICBsaXN0LmFkZChvYmpWYWx1ZSk7
CmVsc2UgaWYoc3RyVmFsdWUgIT0gbnVsbCkKICBsaXN0LmFkZChzdHJWYWx1ZSk7IAoKLy8gQ2xl
YW4gdXAKaWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgTGlzdEFkZCBGbG93
IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqLw==</value>
</Values>
