<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">GetFromKeyedList</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBH
ZXRGcm9tS2V5ZWRMaXN0IEZsb3cKICovCiAgICAKLy8gQ29uc3RhbnRzCmZpbmFsIFN0cmluZyBW
YXJOYW1lS2V5ID0gIktleSI7CmZpbmFsIFN0cmluZyBWYXJOYW1lS2V5ZWRMaXN0ID0gIktleWVk
TGlzdCI7CmZpbmFsIFN0cmluZyBWYXJOYW1lRG9jdW1lbnQgPSAiRG9jIjsKICAgIAovLyBJbml0
aWFsaXplCklEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKLy8gVHJ5IHRv
IGdldCB0aGUga2V5ZWQgTGlzdApJRGF0YSBrZXllZExpc3QgPSBJRGF0YVV0aWwuZ2V0SURhdGEo
aWRjLCBWYXJOYW1lS2V5ZWRMaXN0KTsKCi8vIFRyeSB0byBnZXQgdGhlIGtleQpTdHJpbmcga2V5
ID0gSURhdGFVdGlsLmdldFN0cmluZyhpZGMsIFZhck5hbWVLZXkpOwoKLy8gQ2hlY2sgaW5wdXQg
Zm9yIG51bGwKaWYoa2V5ZWRMaXN0ID09IG51bGwgfHwga2V5ID09IG51bGwpCnsKICBpZGMuZGVz
dHJveSgpOwogIHJldHVybjsKfQoKLy8gR2V0IGtleWVkIExpc3QgQ3Vyc29yCklEYXRhQ3Vyc29y
IGtleWVkTGlzdEN1cnMgPSBrZXllZExpc3QuZ2V0Q3Vyc29yKCk7CmlmKGtleWVkTGlzdEN1cnMg
PT0gbnVsbCkKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRmFpbGVkIHRvIGdldCBjdXJz
b3IgZm9yIEtleWVkTGlzdCIpOwoKSURhdGEgdGhlRG9jID0gSURhdGFVdGlsLmdldElEYXRhKGtl
eWVkTGlzdEN1cnMsIGtleSk7CgovLyBBZGQgdGhlIGtleWVkIGRvY3VtZW50IHRvIHRoZSBwaXBl
bGluZQpJRGF0YVV0aWwucHV0KGlkYywgVmFyTmFtZURvY3VtZW50LCB0aGVEb2MpOwogICAgICAg
IAovLyBDbGVhbiB1cAprZXllZExpc3RDdXJzLmRlc3Ryb3koKTsKaWRjLmRlc3Ryb3koKTsKICAg
IAovKgogKiBXZWIgTWV0aG9kcyBKYXZhIEdldEZyb21LZXllZExpc3QgRmxvdyBlbmRzCiAqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKi8K</value>
</Values>
