<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">SetIterator</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
ZXRJdGVyYXRvciBGbG93CiAqCiAqIGphdmEudXRpbC5TZXQgaXRlcmF0b3IgbWV0aG9kCiAqCiAq
IENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRz
IHJlc2VydmVkLgogKgogKiBJbnB1dDogIFNldCAgICAgIChqYXZhLnV0aWwuU2V0KQogKiAgICAg
ICAgIE9iamVjdCAgIChqYXZhLmxhbmcuT2JqZWN0KQogKiBPdXRwdXQ6IENvbnRhaW5zIChTdHJp
bmcgZnJvbSBib29sZWFuKQogKgogKiBSZXZpc2lvbiBIaXN0b3J5CiAqIDExMDExOCBHT1MgKGdl
aXJtdW5kdXJAc2t5cnIuaXMpIENyZWF0ZWQKICoKICogVW5pdCB0ZXN0CiAqIDExMDExOCBHT1Mg
RmluaXNoZWQKICoKICovCgovLyBJbml0aWFsaXplCklEYXRhQ3Vyc29yIGlkYyA9IEdldEFuZENo
ZWNrQ3Vyc29yKHBpcGVsaW5lKTsKCmphdmEudXRpbC5TZXQgc2V0ID0gRXh0cmFjdFNldChpZGMp
OwoKaWYoc2V0ICE9IG51bGwpCnsKICBPYmplY3QgaXRlcmF0b3IgPSBzZXQuaXRlcmF0b3IoKTsK
ICBJRGF0YVV0aWwucHV0KGlkYywgSVRFUkFUT1IsIGl0ZXJhdG9yKTsKfQoKLy8gQ2xlYW4gdXAK
aWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgU2V0SXRlcmF0b3IgRmxvdyBl
bmRzCiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKi8K</value>
</Values>
