<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IDataUtil_put</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEJ
RG9jdW1lbnQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoIHBpcGVsaW5lQ3Vyc29yLCAiRG9jdW1lbnQi
ICk7Ck9iamVjdAlvYmplY3QgPSBJRGF0YVV0aWwuZ2V0KCBwaXBlbGluZUN1cnNvciwgIm9iamVj
dCIgKTsKT2JqZWN0W10gb2JqZWN0bGlzdCA9IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheSggcGlw
ZWxpbmVDdXJzb3IsICJvYmplY3RsaXN0IiApOwpTdHJpbmcJTGFiZWwgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIkxhYmVsIiApOwppZiAoIERvY3VtZW50ICE9IG51bGwp
IHsKCUlEYXRhQ3Vyc29yIElEQyA9IERvY3VtZW50LmdldEN1cnNvcigpOwoJaWYgKG9iamVjdCAh
PSBudWxsKQoJCUlEYXRhVXRpbC5wdXQoSURDLCBMYWJlbCwgb2JqZWN0KTsKCWVsc2UKCQlJRGF0
YVV0aWwucHV0KElEQywgTGFiZWwsIG9iamVjdGxpc3QpOwoJSURDLmRlc3Ryb3koKTsKfQpwaXBl
bGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
