<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MatcherAppendTail</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXRjaGVyQXBwZW5kVGFpbCBGbG93CiAqCiAqIGphdmEudXRpbC5yZWdleC5NYXRjaGVyIGFwcGVu
ZFRhaWwgbWV0aG9kCiAqCiAqIENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5
cnIuaXMpLiBBbGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDogIE1hdGNoZXIgICAgICAo
amF2YS51dGlsLnJlZ2V4Lk1hdGNoZXIpCiAqICAgICAgICAgU3RyaW5nQnVmZmVyIChqYXZhLmxh
bmcuU3RyaW5nQnVmZmVyKQogKgogKiBPdXRwdXQ6IFN0cmluZ0J1ZmZlciAoamF2YS5sYW5nLlN0
cmluZ0J1ZmZlcikKICoKICogUmV2aXNpb24gSGlzdG9yeQogKiAxMTA5MTIgR09TIChnZWlybXVu
ZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAxMTA5MTIgR09TIEZpbmlz
aGVkCiAqCiAqLwogICAgCi8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hl
Y2tDdXJzb3IocGlwZWxpbmUpOwoKamF2YS51dGlsLnJlZ2V4Lk1hdGNoZXIgbWF0Y2hlciA9IEV4
dHJhY3RNYXRjaGVyKGlkYywgZmFsc2UpOwpqYXZhLmxhbmcuU3RyaW5nQnVmZmVyIHN0cmluZ0J1
ZmZlciA9IEV4dHJhY3RTdHJpbmdCdWZmZXIoaWRjLCB0cnVlKTsKCmlmKG1hdGNoZXIgIT0gbnVs
bCkKICBJRGF0YVV0aWwucHV0CiAgICAgICAgICAoaWRjLCBTVFJJTkdfQlVGRkVSLCBtYXRjaGVy
LmFwcGVuZFRhaWwoc3RyaW5nQnVmZmVyKSk7CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoK
LyoKICogV2ViIE1ldGhvZHMgSmF2YSBNYXRjaGVyQXBwZW5kVGFpbCBGbG93IGVuZHMKICoqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqLwo=</value>
</Values>
