<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">XmlEncodeUpperToNumberic</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBY
bWxFbmNvZGVVcHBlclRvTnVtYmVyaWMgRmxvdwogKgogKiBEZXNjcmlwdGlvbgogKgogKiBDb3B5
cmlnaHQgXHUwMEE5IDIwMDksIEtcdTAwRjZndW4gTHRkICh3d3cua29ndW4uaXMpLiBBbGwgcmln
aHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDogU3RyaW5nIEluCiAqIE91dHB1dDogU3RyaW5nIE91
dAogKgogKiBSZXZpc2lvbiBIaXN0b3J5CiAqIDA5MDUxMSBHT1MgKGdlaXJtdW5kdXJAa29ndW4u
aXMpIENyZWF0ZWQKICoKICogVW5pdCB0ZXN0CiAqIDA5MDUxMSBHT1Mgbm90IGZpbmlzaGVkCiAq
CiAqLwoKLy8gQ29uc3RhbnRzCmZpbmFsIFN0cmluZyBWYXJOYW1lSW4gPSAiSW4iOwpmaW5hbCBT
dHJpbmcgVmFyTmFtZVRocmVzaG9sZCA9ICJUaHJlc2hvbGQiOwpmaW5hbCBTdHJpbmcgVmFyTmFt
ZU91dCA9ICJPdXQiOwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsKaWYoaWRjID09IG51bGwpCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24o
IkZhaWxlZCB0byBnZXQgQ3Vyc29yIHRvIFBpcGVsaW5lIik7CgpjaGFyIHRocmVzaG9sZCA9IEV4
dHJhY3RUaHJlc2hvbGQoaWRjLCBWYXJOYW1lVGhyZXNob2xkKTsKU3RyaW5nIGluID0gSURhdGFV
dGlsLmdldFN0cmluZyhpZGMsIFZhck5hbWVJbik7ClN0cmluZyBvdXQgPSBFbmNvZGVVcHBlclRv
TnVtYmVyaWMoaW4sIHRocmVzaG9sZCk7CgovLyBBZGQgdGhlIHJlc3VsdCB0byB0aGUgcGlwZWxp
bmUKaWYob3V0ICE9IG51bGwpCiAgSURhdGFVdGlsLnB1dChpZGMsIFZhck5hbWVPdXQsIG91dCk7
CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBYbWxF
bmNvZGVVcHBlclRvTnVtYmVyaWMgRmxvdyBlbmRzCiAqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8=</value>
</Values>
