<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sumIntegers</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEJ
aWRJbnB1dERvYyA9IElEYXRhVXRpbC5nZXRJRGF0YSggcGlwZWxpbmVDdXJzb3IsICJwaXBlbGlu
ZSIgKTsKCmludCBuVGVtcD0wOwoKaWYgKCBpZElucHV0RG9jICE9IG51bGwpCnsKCUlEYXRhQ3Vy
c29yIGN1cklucHV0ID0gaWRJbnB1dERvYy5nZXRDdXJzb3IoKTsKCXdoaWxlKGN1cklucHV0Lm5l
eHQoKSkKCXsKCQlpZihjdXJJbnB1dC5nZXRWYWx1ZSgpIGluc3RhbmNlb2YgU3RyaW5nKQoJCXsK
CQkJblRlbXArPUludGVnZXIucGFyc2VJbnQoKFN0cmluZyljdXJJbnB1dC5nZXRWYWx1ZSgpKTsK
CQl9Cgl9CgljdXJJbnB1dC5kZXN0cm95KCk7Cn0KCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yLCAic3VtIiwgblRlbXArIiIgKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwo=</value>
</Values>
