<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">passwd_gen</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZUN1cnMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nIGxlbiA9
IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZUN1cnMsICJsZW4iKTsKaW50IG4gPSBJbnRlZ2VyLnBh
cnNlSW50KGxlbik7IApjaGFyW10gcHcgPSBuZXcgY2hhcltuXTsKaW50IGMgID0gJ0EnOwppbnQg
IHIxID0gMDsKZm9yIChpbnQgaT0wOyBpIDwgbjsgaSsrKSB7CglkbyB7CgkJcjEgPSAoaW50KShN
YXRoLnJhbmRvbSgpICogMyk7CgkJc3dpdGNoKHIxKSB7CgkJCWNhc2UgMDogYyA9ICcwJyArICAo
aW50KShNYXRoLnJhbmRvbSgpICogMTApOyBicmVhazsKCQkJY2FzZSAxOiBjID0gJ2EnICsgIChp
bnQpKE1hdGgucmFuZG9tKCkgKiAyNik7IGJyZWFrOwoJCQljYXNlIDI6IGMgPSAnQScgKyAgKGlu
dCkoTWF0aC5yYW5kb20oKSAqIDI2KTsgYnJlYWs7CgkJfQoJfSB3aGlsZSAoIChjaGFyKWM9PSdJ
JyB8fCAKCQkgIChjaGFyKWM9PSdvJyB8fAoJCSAgKGNoYXIpYz09J08nIHx8CgkJICAoY2hhcilj
PT0nMCcgfHwgCgkJICAoY2hhciljPT0nbCcgfHwKCQkgIChjaGFyKWM9PScxJyB8fAoJCSAgKGNo
YXIpYz09J3EnIHx8CgkJICAoY2hhciljPT0nUScgKTsKCXB3W2ldID0gKGNoYXIpYzsKfQpTdHJp
bmcgcGFzc3dkID0gbmV3IFN0cmluZyhwdyk7CklEYXRhVXRpbC5wdXQocGlwZUN1cnMsICJwYXNz
d2QiLCBwYXNzd2QpOwpwaXBlQ3Vycy5kZXN0cm95KCk7</value>
</Values>
