<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">idataList2json</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQlJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsgCgkJdHJ5IHsKCQkJSURh
dGFbXSBkb2NzID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoaWRjLCAiRG9jdW1lbnRzIik7CgkJ
CWlmIChkb2NzICE9IG51bGwpIHsKCQkJCUpTT05BcnJheSBqc29uQXJyYXkgPSBuZXcgSlNPTkFy
cmF5KCk7CgkJCQlmb3IoaW50IGkgPSAwOyBpIDwgZG9jcy5sZW5ndGg7IGkrKykgewoJCQkJCUlE
YXRhQ3Vyc29yIGN1cnNvciA9IGRvY3NbaV0uZ2V0Q3Vyc29yKCk7CgkJCQkJdHJ5IHsKCQkJCQkJ
d2hpbGUoY3Vyc29yLm5leHQoKSkgewoJCQkJCQkJSlNPTk9iamVjdCBqc29uT2JqID0gbmV3IEpT
T05PYmplY3QoKTsKCQkJCQkJCXdhbGtfaWRhdGEoY3Vyc29yLCBqc29uT2JqKTsKCQkJCQkJCWpz
b25BcnJheS5wdXQoanNvbk9iaik7IAoJCQkJCQl9CgkJCQkJfSBmaW5hbGx5IHsKCQkJCQkJaWYg
KGN1cnNvciAhPSBudWxsKSB7CgkJCQkJCQljdXJzb3IuZGVzdHJveSgpOwoJCQkJCQl9CgkJCQkJ
fQoJCQkJfQoJCQkJSURhdGFVdGlsLnB1dChpZGMsICJqc29uIiwganNvbkFycmF5LnRvU3RyaW5n
KCkpOwoJCQl9CgkJfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsKCQkJdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oZS5nZXRDbGFzcygpICsgIiAiICsgZS5nZXRNZXNzYWdlKCkpOwoJCX0gZmluYWxs
eSB7CgkJCWlkYy5kZXN0cm95KCk7CgkJfQ==</value>
</Values>
