<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">PatternSplit</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBQ
YXR0ZXJuU3BsaXQgRmxvdwogKgogKiBqYXZhLnV0aWwucmVnZXguUGF0dGVybiBzcGxpdCBtZXRo
b2QKICoKICogQ29weXJpZ2h0IChjKSAyMDExLCBTa3lyciBMdGQgKHd3dy5za3lyci5pcykuIEFs
bCByaWdodHMgcmVzZXJ2ZWQuCiAqCiAqIElucHV0OiAgUGF0dGVybiAgICAgICAoamF2YS51dGls
LnJlZ2V4LlBhdHRlcm4pCiAqICAgICAgICAgTGltaXQgICAgICAgICAoU3RyaW5nIC0gb3B0aW9u
YWwgaW50ZWdlcgogKiAgICAgICAgIElucHV0ICAgICAgICAgKGphdmEubGFuZy5DaGFyU2VxdWVu
Y2UgLSBvcHRpb25hbCkKICogICAgICAgICBUZXh0ICAgICAgICAgIChTdHJpbmcgLSBvcHRpb25h
bCkKICoKICogT3V0cHV0OiBTcGxpdCAgIChTdHJpbmcgQXJyYXkpCiAqCiAqIFJldmlzaW9uIEhp
c3RvcnkKICogMTEwOTA5IEdPUyAoZ2Vpcm11bmR1ckBza3lyci5pcykgQ3JlYXRlZAogKgogKiBV
bml0IHRlc3QKICogMTEwOTA5IEdPUyBGaW5pc2hlZAogKgogKi8KCi8vIENvbnN0YW50cwpmaW5h
bCBTdHJpbmcgVmFyTmFtZUxpbWl0ID0gIkxpbWl0IjsKZmluYWwgU3RyaW5nIFZhck5hbWVTcGxp
dCA9ICJTcGxpdCI7CgovLyBJbml0aWFsaXplCklEYXRhQ3Vyc29yIGlkYyA9IEdldEFuZENoZWNr
Q3Vyc29yKHBpcGVsaW5lKTsKCmphdmEudXRpbC5yZWdleC5QYXR0ZXJuIHBhdHRlcm4gPSBFeHRy
YWN0UGF0dGVybihpZGMsIGZhbHNlKTsKamF2YS5sYW5nLkNoYXJTZXF1ZW5jZSBpbnB1dCA9IEV4
dHJhY3RDaGFyU2VxdWVuY2UoaWRjLCBmYWxzZSk7ClN0cmluZyB0ZXh0ID0gSURhdGFVdGlsLmdl
dFN0cmluZyhpZGMsIFRFWFQpOwoKSW50ZWdlciBsaW1pdCA9IEV4dHJhY3RJbnRlZ2VyKGlkYywg
VmFyTmFtZUxpbWl0LCBmYWxzZSk7CgppZihwYXR0ZXJuICE9IG51bGwpCnsKICBpZihpbnB1dCA9
PSBudWxsKQogICAgaWYobGltaXQgPT0gbnVsbCkKICAgICAgSURhdGFVdGlsLnB1dChpZGMsIFZh
ck5hbWVTcGxpdCwgcGF0dGVybi5zcGxpdCh0ZXh0KSk7CiAgICBlbHNlCiAgICAgIElEYXRhVXRp
bC5wdXQoaWRjLCBWYXJOYW1lU3BsaXQsIHBhdHRlcm4uc3BsaXQodGV4dCwgbGltaXQuaW50VmFs
dWUoKSkpOwogIGVsc2UKICAgIGlmKGxpbWl0ID09IG51bGwpCiAgICAgIElEYXRhVXRpbC5wdXQo
aWRjLCBWYXJOYW1lU3BsaXQsIHBhdHRlcm4uc3BsaXQoaW5wdXQpKTsKICAgIGVsc2UKICAgICAg
SURhdGFVdGlsLnB1dChpZGMsIFZhck5hbWVTcGxpdCwgcGF0dGVybi5zcGxpdChpbnB1dCwgbGlt
aXQuaW50VmFsdWUoKSkpOwp9CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2Vi
IE1ldGhvZHMgSmF2YSBQYXR0ZXJuU3BsaXQgRmxvdyBlbmRzCiAqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8K
</value>
</Values>
