<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">cryptString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CglieXRlW10ga2V5ID0gKGJ5dGVbXSkgSURhdGFVdGlsLmdldCggcGlwZWxpbmVDdXJz
b3IsICJjcnlwdEtleSIgKTsKCVN0cmluZwlpbnB1dFN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5wdXRTdHJpbmciICk7CglTdHJpbmcJY3J5cHRBbGdvcml0
aG0gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImNyeXB0QWxnb3JpdGht
IiApOwogICAgICAgIGlmIChjcnlwdEFsZ29yaXRobSA9PSBudWxsIHx8IGNyeXB0QWxnb3JpdGht
Lmxlbmd0aCgpPT0wKSB7CiAgICAgICAgICBjcnlwdEFsZ29yaXRobT0iREVTIjsKICAgICAgICB9
CglTdHJpbmcgc0NyeXB0ZWRTdHJpbmcgPSAiIjsKCXRyeSB7CQoJICAJbXlDcnlwdCBvQ3J5cHQg
PSBuZXcgbXlDcnlwdChrZXksY3J5cHRBbGdvcml0aG0pOwkJCgkJc0NyeXB0ZWRTdHJpbmcgPSBv
Q3J5cHQuZW5jcnlwdEhleFN0cmluZyhpbnB1dFN0cmluZyk7Cgl9IGNhdGNoIChFeGNlcHRpb24g
ZSkgewoJCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCJjcnlwdEVycm9yIixlLmdldE1l
c3NhZ2UoKSk7Cn0KLy8gcGlwZWxpbmUKCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCJj
cnlwdGVkU3RyaW5nIixzQ3J5cHRlZFN0cmluZyk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsK
</value>
</Values>
