<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">GetTime</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBH
ZXRUaW1lIEZsb3cKICoKICogamF2YS51dGlsLkNhbGVuZGFyIGdldFRpbWUgbWV0aG9kCiAqCiAq
IENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRz
IHJlc2VydmVkLgogKgogKiBJbnB1dDogIENhbGVuZGFyICAgKGphdmEudXRpbC5DYWxlbmRhcikK
ICoKICogT3V0cHV0OiBEYXRlICAgICAgIChqYXZhLnV0aWwuRGF0ZSkKICoKICogUmV2aXNpb24g
SGlzdG9yeQogKiAxMTEwMDMgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAq
IFVuaXQgdGVzdAogKiAxMTEwMDMgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJ
RGF0YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgovLyBFeHRyYWN0
IFBhcmFtZXRlcnMKamF2YS51dGlsLkNhbGVuZGFyIGNhbCA9IEV4dHJhY3RDYWxlbmRhcihpZGMs
IGZhbHNlKTsKCmlmKGNhbCAhPSBudWxsKQogIElEYXRhVXRpbC5wdXQoaWRjLCBEQVRFLCBjYWwu
Z2V0VGltZSgpKTsKCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7CgovKgogKiBXZWIgTWV0aG9k
cyBKYXZhIEdldFRpbWUgRmxvdyBlbmRzCiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8K</value>
</Values>
