<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IDataCursor_getValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFD
dXJzb3IgRG9jdW1lbnRDdXJzb3IgPSAoKElEYXRhQ3Vyc29yKSBJRGF0YVV0aWwuZ2V0KCBwaXBl
bGluZUN1cnNvciwgIkRvY3VtZW50Q3Vyc29yIiApICk7CgpJRGF0YVV0aWwucmVtb3ZlKHBpcGVs
aW5lQ3Vyc29yLCAidmFsdWUiKTsKSURhdGFVdGlsLnJlbW92ZShwaXBlbGluZUN1cnNvciwgIkRv
Y3VtZW50Iik7CklEYXRhVXRpbC5yZW1vdmUocGlwZWxpbmVDdXJzb3IsICJEb2N1bWVudExpc3Qi
KTsKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJrZXkiLCBEb2N1bWVudEN1cnNvci5n
ZXRLZXkoKSk7CgppZihEb2N1bWVudEN1cnNvci5nZXRWYWx1ZSgpIGluc3RhbmNlb2YgSURhdGEp
CglJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiRG9jdW1lbnQiLCBEb2N1bWVudEN1cnNv
ci5nZXRWYWx1ZSgpKTsKZWxzZSBpZihEb2N1bWVudEN1cnNvci5nZXRWYWx1ZSgpIGluc3RhbmNl
b2YgSURhdGFbXSkKCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJEb2N1bWVudExpc3Qi
LCBEb2N1bWVudEN1cnNvci5nZXRWYWx1ZSgpKTsKZWxzZSAKCUlEYXRhVXRpbC5wdXQocGlwZWxp
bmVDdXJzb3IsICJ2YWx1ZSIsIERvY3VtZW50Q3Vyc29yLmdldFZhbHVlKCkpOwoKcGlwZWxpbmVD
dXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
