<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">BytesToPipeline</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IAogIHsKICAgIElEYXRhVXRpbCBzcl91dGlsID0gbmV3IElEYXRhVXRpbCgpOyAKICAgIElE
YXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CiAgICBwaXBl
bGluZUN1cnNvci5maXJzdCgic3JfYnl0ZXMiKTsKICAgIGJ5dGVbXSBzcl9ieXRlcyA9IChieXRl
IFtdKSAgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsKICAgIElEYXRhWE1MQ29kZXIgc3JfSURh
dGFYTUxDb2RlciA9IG5ldyBJRGF0YVhNTENvZGVyKCk7CiAgICBJRGF0YSBzcl9JRGF0YSA9IHNy
X0lEYXRhWE1MQ29kZXIuZGVjb2RlRnJvbUJ5dGVzKHNyX2J5dGVzKTsKICAgIHNyX3V0aWwubWVy
Z2Uoc3JfSURhdGEscGlwZWxpbmUpOwogIH0gIApjYXRjaChFeGNlcHRpb24gZSkgCiAgewogICAg
dGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7CiAgfQ==</value>
</Values>
