<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">Add</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBB
ZGQgRmxvdwogKgogKiBqYXZhLnV0aWwuQ2FsZW5kYXIgYWRkIG1ldGhvZAogKgogKiBDb3B5cmln
aHQgKGMpIDIwMTEsIFNreXJyIEx0ZCAod3d3LnNreXJyLmlzKS4gQWxsIHJpZ2h0cyByZXNlcnZl
ZC4KICoKICogSW5wdXQ6ICBDYWxlbmRhciAgIChqYXZhLnV0aWwuQ2FsZW5kYXIpCiAqICAgICAg
ICAgRmllbGQgICAgICAoU3RyaW5nKQogKiAgICAgICAgIEFtb3VudCAgICAgKFN0cmluZyAtIElu
dGVnZXIpCiAqCiAqIFJldmlzaW9uIEhpc3RvcnkKICogMTExMDAzIEdPUyAoZ2Vpcm11bmR1ckBz
a3lyci5pcykgQ3JlYXRlZAogKgogKiBVbml0IHRlc3QKICogMTExMDAzIEdPUyBGaW5pc2hlZAog
KgogKi8KCi8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJzb3Io
cGlwZWxpbmUpOwoKLy8gRXh0cmFjdCBQYXJhbWV0ZXJzCmphdmEudXRpbC5DYWxlbmRhciBjYWwg
PSBFeHRyYWN0Q2FsZW5kYXIoaWRjLCB0cnVlKTsKSW50ZWdlciBhbW91bnQgPSBFeHRyYWN0SW50
ZWdlcihpZGMsIEFNT1VOVCwgdHJ1ZSk7CmludCBmaWVsZCA9IEV4dHJhY3RGaWVsZChpZGMsIHRy
dWUpOwoKY2FsLmFkZChmaWVsZCwgYW1vdW50LmludFZhbHVlKCkpOwoKLy8gQ2xlYW4gdXAKaWRj
LmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgQWRkIEZsb3cgZW5kcwogKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKiovCg==</value>
</Values>
