<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">splitByCharacter</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
CXN0ckxpbmUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInN0ckxpbmUi
ICk7ClN0cmluZwljaGFyYWN0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImNoYXJhY3RlciIgKTsKClN0cmluZyBzdHJQYXJ0T25lID1udWxsOwpTdHJpbmcgc3RyUGFy
dFR3byA9bnVsbDsKCmludCBuRmlyc3Q9LTE7CmludCBuTGFzdCA9LTE7CgppZihzdHJMaW5lICE9
IG51bGwpCnsKCglzdHJMaW5lID0gc3RyTGluZS50cmltKCk7CglpZihzdHJMaW5lLmxlbmd0aCgp
PD0wKQoJCXJldHVybjsKCgluRmlyc3QgPSBzdHJMaW5lLmluZGV4T2YoIGNoYXJhY3RlciApOwoK
CXN0clBhcnRPbmUgPSBzdHJMaW5lLnN1YnN0cmluZygwLG5GaXJzdCk7CgkKCW5MYXN0ID0gc3Ry
TGluZS5sYXN0SW5kZXhPZiggY2hhcmFjdGVyICk7CglzdHJQYXJ0VHdvID0gc3RyTGluZS5zdWJz
dHJpbmcobkxhc3QrMSk7Cgp9CgppZihzdHJQYXJ0T25lIT1udWxsKQpJRGF0YVV0aWwucHV0KCBw
aXBlbGluZUN1cnNvciwgInBhcnRPbmUiLCBzdHJQYXJ0T25lICk7CmlmKHN0clBhcnRUd28hPW51
bGwpCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAicGFydFR3byIsIHN0clBhcnRUd28g
KTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
