<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">localTinvoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCi8vSURh
dGFDdXJzb3IgdG1wY3VycyA9IHRtcC5nZXRDdXJzb3IoKTsKU3RyaW5nIHNlcnZpY2UgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIiRzZXJ2aWNlIiApOwpTdHJpbmcgZm9s
ZGVyID0gc2VydmljZS5zcGxpdCgiOiIpWzBdOwpTdHJpbmcgbmFtZSA9IHNlcnZpY2Uuc3BsaXQo
IjoiKVsxXTsKU3RyaW5nIHRpbWVvdXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgInRpbWVvdXQiICk7CklEYXRhIHBpcGUgPSBJRGF0YVV0aWwuZ2V0SURhdGEoIHBpcGVs
aW5lQ3Vyc29yLCAicGlwZWxpbmUiKTsKdHJ5IHsKCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJz
b3IsICJTZXJ2aWNlVGhyZWFkIiwgU2VydmljZS5kb1RocmVhZEludm9rZShmb2xkZXIsIG5hbWUs
IHBpcGUsIC0xKSk7Ly9Mb25nLnBhcnNlTG9uZyh0aW1lb3V0KSkpOwoJcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOwp9ICBjYXRjaChFeGNlcHRpb24gZSkgewoJcGlwZWxpbmVDdXJzb3IuZGVzdHJv
eSgpOwoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9Cgo=</value>
</Values>
