<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">SetAdd</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
ZXRBZGQgRmxvdwogKgogKiBqYXZhLnV0aWwuU2V0IGFkZCBtZXRob2QKICoKICogQ29weXJpZ2h0
IChjKSAyMDExLCBTa3lyciBMdGQgKHd3dy5za3lyci5pcykuIEFsbCByaWdodHMgcmVzZXJ2ZWQu
CiAqCiAqIElucHV0OiBTZXQgICAgIChqYXZhLnV0aWwuU2V0KQogKiAgICAgICAgT2JqZWN0ICAo
T2JqZWN0KQogKiAgICAgICAgU3RyaW5nICAoU3RyaW5nKQogKgogKiBSZXZpc2lvbiBIaXN0b3J5
CiAqIDExMDExOCBHT1MgKGdlaXJtdW5kdXJAc2t5cnIuaXMpIENyZWF0ZWQKICoKICogVW5pdCB0
ZXN0CiAqIDExMDExOCBHT1MgRmluaXNoZWQKICoKICovCgovLyBJbml0aWFsaXplCklEYXRhQ3Vy
c29yIGlkYyA9IEdldEFuZENoZWNrQ3Vyc29yKHBpcGVsaW5lKTsKCmphdmEudXRpbC5TZXQgc2V0
ID0gRXh0cmFjdFNldChpZGMpOwpqYXZhLmxhbmcuT2JqZWN0IG9iaiA9IEV4dHJhY3RPYmplY3Qo
aWRjKTsKamF2YS5sYW5nLlN0cmluZyBzdHIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgU1RS
SU5HKTsKCmlmKHNldCAhPSBudWxsKQp7CiAgaWYoc3RyICE9IG51bGwpCiAgICBzZXQuYWRkKHN0
cik7CiAgZWxzZQogICAgc2V0LmFkZChvYmopOwp9CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgp
OwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBTZXRBZGQgRmxvdyBlbmRzCiAqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKi8K</value>
</Values>
