<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">remove</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKamF2YS51
dGlsLkxpc3QgbGlzdCA9KGphdmEudXRpbC5MaXN0KSBJRGF0YVV0aWwuZ2V0KCBwaXBlbGluZUN1
cnNvciwgImxpc3QiICk7ClN0cmluZyBzdHJJbmRleCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBp
cGVsaW5lQ3Vyc29yLCAiaW5kZXgiICk7CmludCBuSW5kZXggPSAtMTsKaWYoc3RySW5kZXghPW51
bGwgJiYgc3RySW5kZXgubWF0Y2hlcygiXFxBXFxkK1xcWiIpKQp7CgluSW5kZXggPSBJbnRlZ2Vy
LnBhcnNlSW50KHN0ckluZGV4KTsKfQplbHNlCnsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJJbnZhbGlkIGZvcm1hdCBvZiBpbmRleCIpOwp9CgppZihsaXN0IT1udWxsKQp7CglJRGF0YVV0
aWwucHV0KCBwaXBlbGluZUN1cnNvciwgImVsZW1lbnQiLCBsaXN0LnJlbW92ZShuSW5kZXgpICk7
Cn0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwo=</value>
</Values>
