<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MatcherGroup</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXRjaGVyR3JvdXAgRmxvdwogKgogKiBqYXZhLnV0aWwucmVnZXguTWF0Y2hlciBncm91cCBtZXRo
b2QKICoKICogQ29weXJpZ2h0IChjKSAyMDExLCBTa3lyciBMdGQgKHd3dy5za3lyci5pcykuIEFs
bCByaWdodHMgcmVzZXJ2ZWQuCiAqCiAqIElucHV0OiAgTWF0Y2hlciAgICAgKGphdmEudXRpbC5y
ZWdleC5NYXRjaGVyKQogKiAgICAgICAgIEdyb3VwSW5kZXggIChTdHJpbmcgLSBPcHRpb25hbCBJ
bnRlZ2VyKQogKgogKiBPdXRwdXQ6IEdyb3VwICAgICAgIChTdHJpbmcgLSBPcHRpb25hbCkKICoK
ICogUmV2aXNpb24gSGlzdG9yeQogKiAxMTA5MTIgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBD
cmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAxMTA5MTIgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8g
Q29uc3RhbnRzCmZpbmFsIFN0cmluZyBWYXJOYW1lR3JvdXBJbmRleCA9ICJHcm91cEluZGV4IjsK
ZmluYWwgU3RyaW5nIFZhck5hbWVHcm91cCA9ICJHcm91cCI7CgovLyBJbml0aWFsaXplCklEYXRh
Q3Vyc29yIGlkYyA9IEdldEFuZENoZWNrQ3Vyc29yKHBpcGVsaW5lKTsKCmphdmEudXRpbC5yZWdl
eC5NYXRjaGVyIG1hdGNoZXIgPSBFeHRyYWN0TWF0Y2hlcihpZGMsIGZhbHNlKTsKSW50ZWdlciBn
cm91cEluZGV4ID0gRXh0cmFjdEludGVnZXIoaWRjLCBWYXJOYW1lR3JvdXBJbmRleCwgZmFsc2Up
OwoKaWYobWF0Y2hlciAhPSBudWxsKQp7CiAgaWYoZ3JvdXBJbmRleCA9PSBudWxsKQogICAgSURh
dGFVdGlsLnB1dChpZGMsIFZhck5hbWVHcm91cCwgbWF0Y2hlci5ncm91cCgpKTsKICBlbHNlCiAg
ICBJRGF0YVV0aWwucHV0KGlkYywgVmFyTmFtZUdyb3VwLCBtYXRjaGVyLmdyb3VwKGdyb3VwSW5k
ZXguaW50VmFsdWUoKSkpOwp9CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2Vi
IE1ldGhvZHMgSmF2YSBNYXRjaGVyR3JvdXAgRmxvdyBlbmRzCiAqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8K
</value>
</Values>
