<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IpInRange</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaW5QaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgbWlu
ID0gSURhdGFVdGlsLmdldFN0cmluZyhpblBpcGVsaW5lLCAicmFuZ2Vfc3RhcnRzIik7IApTdHJp
bmcgbWF4ID0gSURhdGFVdGlsLmdldFN0cmluZyhpblBpcGVsaW5lLCAicmFuZ2VfZW5kcyIpOyAK
U3RyaW5nIGlwID0gSURhdGFVdGlsLmdldFN0cmluZyhpblBpcGVsaW5lLCAiaXBfYWRkcmVzcyIp
OyAKaW5QaXBlbGluZS5kZXN0cm95KCk7Cgp0cnkgewoJbG9uZyBsbWluID0gaG9zdDJsb25nKG1p
bik7Cglsb25nIGxtYXggPSBob3N0MmxvbmcobWF4KTsKCWxvbmcgbGlwID0gaG9zdDJsb25nKGlw
KTsgCglTdHJpbmcgcmVzdWx0ID0gInRydWUiOwoJCiAgIGlmIChsaXAgPCBsbWluKSAKICAgICAg
IHsKICAgICAgIHJlc3VsdCA9ICJmYWxzZSI7CiAgICAgICB9IGVsc2UgaWYgKGxpcCA+IGxtYXgp
IHsKICAgICAgIHJlc3VsdCA9ICJmYWxzZSI7CiAgICAgICB9CklEYXRhQ3Vyc29yIG91dFBpcGVs
aW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQob3V0UGlwZWxpbmUsICJJ
c0luUmFuZ2UiLHJlc3VsdCk7Cm91dFBpcGVsaW5lLmRlc3Ryb3koKTsKfSAKY2F0Y2ggKEV4Y2Vw
dGlvbiBlKSB7CiAgICAgICAgICAgIGUucHJpbnRTdGFja1RyYWNlKCk7CiAgICAgICAgfQoK</value>
</Values>
