<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">CreateHashSet</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBD
cmVhdGVIYXNoU2V0IEZsb3cKICoKICogQ3JlYXRlIG5ldyBqYXZhLnV0aWwuSGFzaE1hcAogKgog
KiBDb3B5cmlnaHQgKGMpIDIwMTEsIFNreXJyIEx0ZCAod3d3LnNreXJyLmlzKS4gQWxsIHJpZ2h0
cyByZXNlcnZlZC4KICoKICogT3V0cHV0OiBOZXcgSGFzaE1hcCBvYmplY3QKICoKICogUmV2aXNp
b24gSGlzdG9yeQogKiAxMTAxMTggR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAq
CiAqIFVuaXQgdGVzdAogKiAxMTAxMTggR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gQ29uc3RhbnRz
CmZpbmFsIFN0cmluZyBWYXJOYW1lSGFzaFNldCA9ICJIYXNoU2V0IjsKCi8vIEluaXRpYWxpemUK
SURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJzb3IocGlwZWxpbmUpOwoKamF2YS51dGls
Lkhhc2hTZXQgaGFzaFNldCA9IG5ldyBqYXZhLnV0aWwuSGFzaFNldCgpOwoKLy8gQWRkIHRoZSBy
ZXN1bHQgdG8gdGhlIHBpcGVsaW5lCklEYXRhVXRpbC5wdXQoaWRjLCBWYXJOYW1lSGFzaFNldCwg
aGFzaFNldCk7CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMg
SmF2YSBDcmVhdGVIYXNoU2V0IEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
