<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MatcherGroupCount</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXRjaGVyR3JvdXBDb3VudCBGbG93CiAqCiAqIGphdmEudXRpbC5yZWdleC5NYXRjaGVyIGdyb3Vw
Q291bnQgbWV0aG9kCiAqCiAqIENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5
cnIuaXMpLiBBbGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDogIE1hdGNoZXIgICAgIChq
YXZhLnV0aWwucmVnZXguTWF0Y2hlcikKICoKICogT3V0cHV0OiBHcm91cENvdW50ICAoU3RyaW5n
IC0gSW50ZWdlcikKICoKICogUmV2aXNpb24gSGlzdG9yeQogKiAxMTA5MTIgR09TIChnZWlybXVu
ZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAxMTA5MTIgR09TIEZpbmlz
aGVkCiAqCiAqLwoKLy8gQ29uc3RhbnRzCmZpbmFsIFN0cmluZyBWYXJOYW1lR3JvdXBDb3VudCA9
ICJHcm91cENvdW50IjsKCi8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hl
Y2tDdXJzb3IocGlwZWxpbmUpOwoKamF2YS51dGlsLnJlZ2V4Lk1hdGNoZXIgbWF0Y2hlciA9IEV4
dHJhY3RNYXRjaGVyKGlkYywgZmFsc2UpOwoKaWYobWF0Y2hlciAhPSBudWxsKQogIElEYXRhVXRp
bC5wdXQoaWRjLCBWYXJOYW1lR3JvdXBDb3VudCwgSW50ZWdlci50b1N0cmluZyhtYXRjaGVyLmdy
b3VwQ291bnQoKSkpOwoKLy8gQ2xlYW4gdXAKaWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRo
b2RzIEphdmEgTWF0Y2hlckdyb3VwQ291bnQgRmxvdyBlbmRzCiAqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8K
</value>
</Values>
