<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcEMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCkFycmF5TGlzdCBhbCA9IChB
cnJheUxpc3QpIElEYXRhVXRpbC5nZXQocEMsICJBcnJheUxpc3QiKTsKT2JqZWN0IG9iamVjdCA9
IElEYXRhVXRpbC5nZXQocEMsICJvYmplY3QiKTsKU3RyaW5nIGluZGV4ID0gSURhdGFVdGlsLmdl
dFN0cmluZyhwQywgImluZGV4Iik7CgppZiAoYWwgPT0gbnVsbCkgewoJYWwgPSBuZXcgQXJyYXlM
aXN0KCk7CglJRGF0YVV0aWwucHV0KHBDLCAiQXJyYXlMaXN0IiwgYWwgKTsKfQoKaWYgKGluZGV4
ID09IG51bGwgfHwgaW5kZXggPT0gIiIpIHsKCWFsLmFkZChvYmplY3QpOwp9IGVsc2UgewoJYWwu
YWRkKEludGVnZXIucGFyc2VJbnQoaW5kZXgpLG9iamVjdCk7Cn0KCnBDLmRlc3Ryb3koKTs=</value>
</Values>
