<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">CompilePattern</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBD
b21waWxlUGF0dGVybiBGbG93CiAqCiAqIGphdmEudXRpbC5yZWdleC5QYXR0ZXJuIGNvbXBpbGUg
bWV0aG9kCiAqCiAqIENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMp
LiBBbGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDogIFJlZ0V4IChTdHJpbmcpCiAqICAg
ICAgICAgRmxhZ3MgKFN0cmluZyAtIG9wdGlvbmFsKQogKgogKiBPdXRwdXQ6IFBhdHRlcm4gKGph
dmEudXRpbC5yZWdleC5QYXR0ZXJuKQogKgogKiBSZXZpc2lvbiBIaXN0b3J5CiAqIDExMDkwOCBH
T1MgKGdlaXJtdW5kdXJAc2t5cnIuaXMpIENyZWF0ZWQKICoKICogVW5pdCB0ZXN0CiAqIDExMDkw
OCBHT1MgRmluaXNoZWQKICoKICovCgovLyBDb25zdGFudHMKZmluYWwgU3RyaW5nIFZhck5hbWVG
bGFncyA9ICJGbGFncyI7CgovLyBJbml0aWFsaXplCklEYXRhQ3Vyc29yIGlkYyA9IEdldEFuZENo
ZWNrQ3Vyc29yKHBpcGVsaW5lKTsKClN0cmluZyByZWdFeCA9IElEYXRhVXRpbC5nZXRTdHJpbmco
aWRjLCBSRUdFWCk7ClN0cmluZ1tdIGZsYWdzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGlk
YywgVmFyTmFtZUZsYWdzKTsKCmlmKHJlZ0V4ID09IG51bGwpCiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oIlJlZ0V4IHBhcmFtZXRlciBpcyB1bmRlZmluZWQiKTsKCmlmKGZsYWdzID09IG51
bGwpCiAgSURhdGFVdGlsLnB1dChpZGMsIFBBVFRFUk4sIGphdmEudXRpbC5yZWdleC5QYXR0ZXJu
LmNvbXBpbGUKICAgICAgICAgIChyZWdFeCkpOwplbHNlCiAgSURhdGFVdGlsLnB1dChpZGMsIFBB
VFRFUk4sIGphdmEudXRpbC5yZWdleC5QYXR0ZXJuLmNvbXBpbGUKICAgICAgICAgIChyZWdFeCwg
Q3JlYXRlRmxhZ3MoZmxhZ3MpKSk7CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICog
V2ViIE1ldGhvZHMgSmF2YSBDb21waWxlUGF0dGVybiBGbG93IGVuZHMKICoqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqLwo=</value>
</Values>
