<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
dHJpbmdCdWZmZXJUb1N0cmluZyBGbG93CiAqCiAqIGphdmEubGFuZy5TdHJpbmdCdWZmZXIgdG9T
dHJpbmcgTWV0aG9kCiAqCiAqIENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5
cnIuaXMpLiBBbGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDogIFN0cmluZ0J1ZmZlciAo
amF2YS5sYW5nLlN0cmluZ0J1ZmZlcikKICoKICogT3V0cHV0OiBUb1N0cmluZyAgICAgKFN0cmlu
ZykKICoKICogUmV2aXNpb24gSGlzdG9yeQogKiAxMTA5MTUgR09TIChnZWlybXVuZHVyQHNreXJy
LmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAxMTA5MTUgR09TIEZpbmlzaGVkCiAqCiAq
LwoKLy8gQ29uc3RhbnRzCmZpbmFsIFN0cmluZyBWYXJOYW1lVG9TdHJpbmcgPSAiVG9TdHJpbmci
OwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBl
bGluZSk7CgpqYXZhLmxhbmcuU3RyaW5nQnVmZmVyIHNiID0gRXh0cmFjdFN0cmluZ0J1ZmZlcihp
ZGMsIGZhbHNlKTsKCmlmKHNiICE9IG51bGwpCiAgSURhdGFVdGlsLnB1dChpZGMsIFZhck5hbWVU
b1N0cmluZywgc2IudG9TdHJpbmcoKSk7CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoK
ICogV2ViIE1ldGhvZHMgSmF2YSBTdHJpbmdCdWZmZXJUb1N0cmluZyBGbG93IGVuZHMKICoqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqLwo=</value>
</Values>
