<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">SetClear</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
ZXRDbGVhciBGbG93CiAqCiAqIGphdmEudXRpbC5TZXQgY2xlYXIgbWV0aG9kCiAqCiAqIENvcHly
aWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRzIHJlc2Vy
dmVkLgogKgogKiBJbnB1dDogU2V0IChqYXZhLnV0aWwuU2V0KQogKgogKiBSZXZpc2lvbiBIaXN0
b3J5CiAqIDExMDExOCBHT1MgKGdlaXJtdW5kdXJAc2t5cnIuaXMpIENyZWF0ZWQKICoKICogVW5p
dCB0ZXN0CiAqIDExMDExOCBHT1MgRmluaXNoZWQKICoKICovCgovLyBJbml0aWFsaXplCklEYXRh
Q3Vyc29yIGlkYyA9IEdldEFuZENoZWNrQ3Vyc29yKHBpcGVsaW5lKTsKCmphdmEudXRpbC5TZXQg
c2V0ID0gRXh0cmFjdFNldChpZGMpOwoKaWYoc2V0ICE9IG51bGwpCiAgc2V0LmNsZWFyKCk7Cgov
LyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBTZXRDbGVh
ciBGbG93IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqLwo=</value>
</Values>
