<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">CreateHashMap</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBD
cmVhdGVIYXNoTWFwIEZsb3cKICoKICogQ3JlYXRlIG5ldyBqYXZhLnV0aWwuSGFzaE1hcAogKgog
KiBDb3B5cmlnaHQgXHUwMEE5IDIwMDksIEtcdTAwRjZndW4gTHRkICh3d3cua29ndW4uaXMpLiBB
bGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBPdXRwdXQ6IE5ldyBIYXNoTWFwIG9iamVjdAogKgog
KiBSZXZpc2lvbiBIaXN0b3J5CiAqIDA5MDMxNiBHT1MgKGdlaXJtdW5kdXJAa29ndW4uaXMpIENy
ZWF0ZWQKICoKICogVW5pdCB0ZXN0CiAqIDA5MDMxNiBHT1Mgbm90IGZpbmlzaGVkCiAqCiAqLwoK
Ly8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGlu
ZSk7CgpqYXZhLnV0aWwuSGFzaE1hcCBoYXNoTWFwID0gbmV3IGphdmEudXRpbC5IYXNoTWFwKCk7
CgovLyBBZGQgdGhlIHJlc3VsdCB0byB0aGUgcGlwZWxpbmUKSURhdGFVdGlsLnB1dChpZGMsIE1B
UCwgaGFzaE1hcCk7CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhv
ZHMgSmF2YSBDcmVhdGVIYXNoTWFwIEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
