<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MapEntrySet</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXBFbnRyeVNldCBGbG93CiAqCiAqIGphdmEudXRpbC5NYXAgZW50cnlTZXQgbWV0aG9kCiAqCiAq
IENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRz
IHJlc2VydmVkLgogKgogKiBJbnB1dDogTWFwIChqYXZhLnV0aWwuTWFwKQogKiBPdXRwdXQ6IFNl
dCAoamF2YS51dGlsLlNldCkKICoKICogUmV2aXNpb24gSGlzdG9yeQogKiAxMTAxMjAgR09TIChn
ZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAxMTAxMjAgR09T
IEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBHZXRBbmRD
aGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0aWwuTWFwIG1hcCA9IEV4dHJhY3RNYXAoaWRj
LCBmYWxzZSk7CgpJRGF0YVV0aWwucHV0KGlkYywgU0VULCBtYXAuZW50cnlTZXQoKSk7CgovLyBD
bGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBNYXBFbnRyeVNl
dCBGbG93IGVuZHMKICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqLwo=</value>
</Values>
