<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IDataUtil_get_first_key</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEJ
RG9jdW1lbnREVCA9IElEYXRhVXRpbC5nZXRJRGF0YSggcGlwZWxpbmVDdXJzb3IsICJrZXlfYmVs
b3ciICk7ClN0cmluZyBjb3VudCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCAiY291bnQiKTsKaWYgKGNvdW50ID09IG51bGwpCgljb3VudD0iMCI7CmludCBjbnQgPSBJbnRl
Z2VyLnBhcnNlSW50KGNvdW50KTsKaWYgKCBEb2N1bWVudERUICE9IG51bGwpIHsKCUlEYXRhQ3Vy
c29yIGRvY0MgPSBEb2N1bWVudERULmdldEN1cnNvcigpOwoJZG9jQy5maXJzdCgpOwoJZm9yIChp
bnQgaT0wOyBpPGNudDsgaSsrKQoJCWRvY0MubmV4dCgpOwoJSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3IsICJrZXkiLCBkb2NDLmdldEtleSgpICk7Cn0KCnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTs=</value>
</Values>
