<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">GetField</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBH
ZXRGaWVsZCBGbG93CiAqCiAqIEdldCBqYXZhLnV0aWwuQ2FsZW5kYXIgRmllbGRzIENvbnN0YW50
cwogKgogKiBDb3B5cmlnaHQgKGMpIDIwMTEsIFNreXJyIEx0ZCAod3d3LnNreXJyLmlzKS4gQWxs
IHJpZ2h0cyByZXNlcnZlZC4KICoKICogSW5wdXQ6ICBGaWVsZCAgICAgIChTdHJpbmcpCiAqCiAq
IE91dHB1dDogVmFsdWUgICAgICAoU3RyaW5nIC0gSW50ZWdlcikKICoKICogUmV2aXNpb24gSGlz
dG9yeQogKiAxMTEwMDQgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVu
aXQgdGVzdAogKiAxMTEwMDQgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJRGF0
YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgovLyBFeHRyYWN0IFBh
cmFtZXRlcnMKaW50IGZpZWxkID0gRXh0cmFjdEZpZWxkKGlkYywgZmFsc2UpOwoKSURhdGFVdGls
LnB1dChpZGMsIFZBTFVFLCBJbnRlZ2VyLnRvU3RyaW5nKGZpZWxkKSk7CgovLyBDbGVhbiB1cApp
ZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhvZHMgSmF2YSBHZXRGaWVsZCBGbG93IGVuZHMK
ICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqLwo=</value>
</Values>
