<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getItems</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCi8vIGxpc3QKSURhdGFbXQlsaXN0ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoIHBp
cGVsaW5lQ3Vyc29yLCAibGlzdCIgKTsKU3RyaW5nIHN0ckF0dHIgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImF0dHIiKTsKU3RyaW5nIHN0clZhbHVlID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJ2YWx1ZSIpOwpJRGF0YUN1cnNvciBjdXJzID0g
bnVsbDsKSURhdGFbXSBhbnMgPSBudWxsOwpJRGF0YVtdIGl0ZW0gPSBuZXcgSURhdGFbbGlzdC5s
ZW5ndGhdOwppbnQgY291bnQ9MDsKdHJ5IHsKICBmb3IgKGludCBpPTA7IGk8bGlzdC5sZW5ndGg7
IGkrKykgewoJY3VycyA9IGxpc3RbaV0uZ2V0Q3Vyc29yKCk7CglpZiAoIHN0clZhbHVlLmVxdWFs
cyggSURhdGFVdGlsLmdldFN0cmluZyggY3Vycywgc3RyQXR0cikgKSApIHsKCQlpdGVtW2NvdW50
KytdID0gbGlzdFtpXTsKCX0KCWN1cnMuZGVzdHJveSgpOwogIH0KICBhbnMgPSBuZXcgSURhdGFb
Y291bnRdOwogIGZvciAoaW50IGk9MDsgaTxjb3VudDsgaSsrKQoJYW5zW2ldID0gaXRlbVtpXTsK
fSBjYXRjaChOdW1iZXJGb3JtYXRFeGNlcHRpb24gZSkge30KCklEYXRhVXRpbC5wdXQoIHBpcGVs
aW5lQ3Vyc29yLCAiaXRlbSIsIGFucyAgKTsKCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
