<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MatcherFind</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXRjaGVyRmluZCBGbG93CiAqCiAqIGphdmEudXRpbC5yZWdleC5NYXRjaGVyIGZpbmQgbWV0aG9k
CiAqCiAqIENvcHlyaWdodCAoYykgMjAxMSwgU2t5cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwg
cmlnaHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDogIE1hdGNoZXIgKGphdmEudXRpbC5yZWdleC5N
YXRjaGVyKQogKiAgICAgICAgIFN0YXJ0ICAgKFN0cmluZyAtIE9wdGlvbmFsIEludGVnZXIpCiAq
CiAqIE91dHB1dDogRmluZCAgICAoU3RyaW5nIC0gQm9vbGVhbikKICoKICogUmV2aXNpb24gSGlz
dG9yeQogKiAxMTA5MDkgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVu
aXQgdGVzdAogKiAxMTA5MDkgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gQ29uc3RhbnRzCmZpbmFs
IFN0cmluZyBWYXJOYW1lU3RhcnQgPSAiU3RhcnQiOwpmaW5hbCBTdHJpbmcgVmFyTmFtZUZpbmQg
PSAiRmluZCI7CgovLyBJbml0aWFsaXplCklEYXRhQ3Vyc29yIGlkYyA9IEdldEFuZENoZWNrQ3Vy
c29yKHBpcGVsaW5lKTsKCmphdmEudXRpbC5yZWdleC5NYXRjaGVyIG1hdGNoZXIgPSBFeHRyYWN0
TWF0Y2hlcihpZGMsIGZhbHNlKTsKSW50ZWdlciBzdGFydCA9IEV4dHJhY3RJbnRlZ2VyKGlkYywg
VmFyTmFtZVN0YXJ0LCBmYWxzZSk7CgppZihtYXRjaGVyICE9IG51bGwpCnsKICBpZihzdGFydCA9
PSBudWxsKQogICAgSURhdGFVdGlsLnB1dChpZGMsIFZhck5hbWVGaW5kLCAKICAgICAgICAgICAg
Qm9vbGVhbi50b1N0cmluZyhtYXRjaGVyLmZpbmQoKSkpOwogIGVsc2UKICAgIElEYXRhVXRpbC5w
dXQoaWRjLCBWYXJOYW1lRmluZCwgCiAgICAgICAgICAgIEJvb2xlYW4udG9TdHJpbmcobWF0Y2hl
ci5maW5kKHN0YXJ0LmludFZhbHVlKCkpKSk7Cn0KCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7
CgovKgogKiBXZWIgTWV0aG9kcyBKYXZhIE1hdGNoZXJGaW5kIEZsb3cgZW5kcwogKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKiovCg==</value>
</Values>
