<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getLogFilePath</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5CnsKICAvLyBwaXBlbGluZQogIElEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CiAgU3RyaW5nICBsb2dnZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBw
aXBlbGluZUN1cnNvciwgImxvZ2dlciIgKTsKICBTdHJpbmcgIGZpbGVkYXRlID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJmaWxlZGF0ZSIgKTsKICBTdHJpbmcgIGZpbGVw
YXRoID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJmaWxlcGF0aCIgKTsK
ICBTdHJpbmcgczsKICBpZiggZmlsZXBhdGggPT0gbnVsbCB8fCBmaWxlcGF0aC5sZW5ndGgoKSA9
PSAwKSAgCglzID0gbmV3IFN0cmluZyhsb2dwYXRoICsgbG9nZ2VyICsgIl8iICsgZmlsZWRhdGUg
KyAiLmxvZyIpOwogIGVsc2UKICAgICAgICBzID0gbmV3IFN0cmluZyhmaWxlcGF0aCArIGxvZ2dl
ciArICJfIiArIGZpbGVkYXRlICsgIi5sb2ciKTsKCgogIC8vIHBpcGVsaW5lCiAgSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3IsICJsb2dmaWxlcGF0aCIsIHMgKTsKICBwaXBlbGluZUN1cnNv
ci5kZXN0cm95KCk7Cn0KY2F0Y2goRXhjZXB0aW9uIGUgKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oIGUuZ2V0TWVzc2FnZSgpICk7Cn0gICA=</value>
</Values>
