<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IDataCursor_next</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFD
dXJzb3IgRG9jdW1lbnRDdXJzb3IgPSAoKElEYXRhQ3Vyc29yKSBJRGF0YVV0aWwuZ2V0KCBwaXBl
bGluZUN1cnNvciwgIkRvY3VtZW50Q3Vyc29yIiApICk7ClN0cmluZyBrZXkgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAibmV4dF9rZXkiKTsKaWYgKGtleSA9PSBudWxsKSB7
CglpZiAoRG9jdW1lbnRDdXJzb3IubmV4dCgpID09IHRydWUpCgkJSURhdGFVdGlsLnB1dCggcGlw
ZWxpbmVDdXJzb3IsICJoYXNOZXh0IiwgInRydWUiICk7CgllbHNlIAoJCUlEYXRhVXRpbC5wdXQo
IHBpcGVsaW5lQ3Vyc29yLCAiaGFzTmV4dCIsICJmYWxzZSIgKTsKfSBlbHNlIHsKCWlmIChEb2N1
bWVudEN1cnNvci5uZXh0KGtleSkgPT0gdHJ1ZSkKCQlJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1
cnNvciwgImhhc05leHQiLCAidHJ1ZSIgKTsKCWVsc2UgCgkJSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3IsICJoYXNOZXh0IiwgImZhbHNlIiApOwp9CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3ko
KTs=</value>
</Values>
