<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">GetInstance</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBH
ZXRJbnN0YW5jZSBGbG93CiAqCiAqIGphdmEudXRpbC5DYWxlbmRhciBnZXRJbnN0YW5jZSBzdGF0
aWMgbWV0aG9kCiAqCiAqIFRvRG86IFN1cHBvcnQgTG9jYWxlIGFuZCBUaW1lWm9uZS4gU3VwcG9y
dCBEYXRlIGFzIElucHV0IHRocm91Z2ggc2V0VGltZQogKgogKiBDb3B5cmlnaHQgKGMpIDIwMTEs
IFNreXJyIEx0ZCAod3d3LnNreXJyLmlzKS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4KICoKICogSW5w
dXQ6ICBDbGFzc1R5cGUgIChTdHJpbmcgLSBPcHRpb25hbCkKICoKICogT3V0cHV0OiBDYWxlbmRh
ciAgIChqYXZhLnV0aWwuQ2FsZW5kYXIpCiAqCiAqIFJldmlzaW9uIEhpc3RvcnkKICogMTExMDAz
IEdPUyAoZ2Vpcm11bmR1ckBza3lyci5pcykgQ3JlYXRlZAogKgogKiBVbml0IHRlc3QKICogMTEx
MDAzIEdPUyBGaW5pc2hlZAogKgogKi8KCi8vIENvbnN0YW50cwpmaW5hbCBTdHJpbmcgVmFyTmFt
ZUNsYXNzVHlwZSA9ICJDbGFzc1R5cGUiOwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBpZGMg
PSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpTdHJpbmcgQ2xhc3NUeXBlID0gSURhdGFV
dGlsLmdldFN0cmluZyhpZGMsIFZhck5hbWVDbGFzc1R5cGUpOwoKaWYoQ2xhc3NUeXBlICE9IG51
bGwgJiYgQ2xhc3NUeXBlLmVxdWFsc0lnbm9yZUNhc2UoIkdyZWdvcmlhbkNhbGVuZGFyIikpCnsK
ICBJRGF0YVV0aWwucHV0KGlkYywgQ0FMRU5EQVIsIGphdmEudXRpbC5HcmVnb3JpYW5DYWxlbmRh
ci5nZXRJbnN0YW5jZSgpKTsKfQplbHNlCnsKICBJRGF0YVV0aWwucHV0KGlkYywgQ0FMRU5EQVIs
IGphdmEudXRpbC5DYWxlbmRhci5nZXRJbnN0YW5jZSgpKTsKfQoKLy8gQ2xlYW4gdXAKaWRjLmRl
c3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRob2RzIEphdmEgR2V0SW5zdGFuY2UgRmxvdyBlbmRzCiAq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKi8K</value>
</Values>
