<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">StringVectorToArray</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBT
dHJpbmdWZWN0b3JUb0FycmF5IEZsb3cKICovCgovLyBDb25zdGFudHMKZmluYWwgU3RyaW5nIFZh
ck5hbWVTdHJpbmdWZWN0b3IgPSAiU3RyaW5nVmVjdG9yIjsKZmluYWwgU3RyaW5nIFZhck5hbWVT
dHJpbmdBcnJheSA9ICJBcnJheSI7CgovLyBJbml0aWFsaXplCklEYXRhQ3Vyc29yIGlkYyA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOwppZihpZGMgPT0gbnVsbCkKICB0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbigiRmFpbGVkIHRvIGdldCBDdXJzb3IgdG8gUGlwZWxpbmUiKTsKCi8vIFRyeSB0byBn
ZXQgdGhlIFN0cmluZyBWZWN0b3IKT2JqZWN0IHN0cmluZ1ZlY3Rvck9iamVjdCA9IElEYXRhVXRp
bC5nZXQoaWRjLCBWYXJOYW1lU3RyaW5nVmVjdG9yKTsKCi8vIENyZWF0ZSB0aGUgQ29udGFpbnMg
VmFyaWFibGVzCgppZihzdHJpbmdWZWN0b3JPYmplY3QgaW5zdGFuY2VvZiBqYXZhLnV0aWwuVmVj
dG9yKQp7CiAgamF2YS51dGlsLlZlY3RvciB2ZWN0b3IgPSAoamF2YS51dGlsLlZlY3RvcilzdHJp
bmdWZWN0b3JPYmplY3Q7CiAgU3RyaW5nW10gYXJyYXkgPSBuZXcgU3RyaW5nW3ZlY3Rvci5zaXpl
KCldOwogIHZlY3Rvci50b0FycmF5KGFycmF5KTsKICAKICBJRGF0YVV0aWwucHV0CiAgICAgICAg
ICAoCiAgICAgICAgICBpZGMsIAogICAgICAgICAgVmFyTmFtZVN0cmluZ0FycmF5LCAKICAgICAg
ICAgIGFycmF5CiAgICAgICAgICApOwp9CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoK
ICogV2ViIE1ldGhvZHMgSmF2YSBTdHJpbmdWZWN0b3JUb0FycmF5IEZsb3cgZW5kcwogKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKiov</value>
</Values>
