<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MapContainsKey</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
YXBDb250YWluc0tleSBGbG93CiAqCiAqIGphdmEudXRpbC5NYXAgY29udGFpbnNLZXkgbWV0aG9k
CiAqCiAqIENvcHlyaWdodCBcdTAwQTkgMjAwOSwgS1x1MDBGNmd1biBMdGQgKHd3dy5rb2d1bi5p
cykuIEFsbCByaWdodHMgcmVzZXJ2ZWQuCiAqCiAqIElucHV0OgogKiAgIGphdmEudXRpbC5NYXAg
TWFwCiAqICAgT2JqZWN0ICAgICAgICBLZXkKICogICBTdHJpbmcgICAgICAgIEtleVN0cmluZwog
KiBPdXRwdXQ6CiAqICAgYm9vbGVhbiAgICAgICBDb250YWluc0tleQogKgogKiBSZXZpc2lvbiBI
aXN0b3J5CiAqIDA5MDMxNiBHT1MgKGdlaXJtdW5kdXJAa29ndW4uaXMpIENyZWF0ZWQKICoKICog
VW5pdCB0ZXN0CiAqIDA5MDMxNiBHT1Mgbm90IGZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6
ZQpJRGF0YUN1cnNvciBpZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0
aWwuTWFwIG1hcCA9IEV4dHJhY3RNYXAoaWRjKTsKCk9iamVjdCBvYmpLZXkgPSBJRGF0YVV0aWwu
Z2V0KGlkYywgS0VZKTsKU3RyaW5nIHN0cktleSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjLCBL
RVlfU1RSSU5HKTsKCmJvb2xlYW4gY29udGFpbnNLZXkgPSBmYWxzZTsKCmlmKG9iaktleSAhPSBu
dWxsKQogIGNvbnRhaW5zS2V5ID0gbWFwLmNvbnRhaW5zS2V5KG9iaktleSk7CmVsc2UgaWYoc3Ry
S2V5ICE9IG51bGwpCiAgY29udGFpbnNLZXkgPSBtYXAuY29udGFpbnNLZXkoc3RyS2V5KTsKCklE
YXRhVXRpbC5wdXQoaWRjLCBDT05UQUlOU19LRVksIEJvb2xlYW4udG9TdHJpbmcoY29udGFpbnNL
ZXkpKTsKCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7CgovKgogKiBXZWIgTWV0aG9kcyBKYXZh
IE1hcENvbnRhaW5zS2V5IEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
