<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">MessageFormat</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBN
ZXNzYWdlRm9ybWF0IEZsb3cKICoKICogQSB3cmFwZXIgYXJvdW5kIHRoZSBqYXZhLnRleHQuTWVz
c2FnZUZvcm1hdCBmb3JtYXQgc3RhdGljIG1ldGhvZAogKgogKiBodHRwOi8vZG9jcy5vcmFjbGUu
Y29tL2phdmFzZS83L2RvY3MvYXBpL2phdmEvdGV4dC9NZXNzYWdlRm9ybWF0Lmh0bWwKICoKICog
Q29weXJpZ2h0IChjKSAyMDExLCBTa3lyciBlaGYgKHd3dy5za3lyci5pcykuIEFsbCByaWdodHMg
cmVzZXJ2ZWQuCiAqCiAqIElucHV0OiAgUGF0dGVybiAgICAgIChTdHJpbmcpCiAqICAgICAgICAg
T2JqZWN0QXJyYXkgIChPYmplY3RBcnJheSkKICogT3V0cHV0OiBSZXN1bHQgICAgICAgKFN0cmlu
ZykKICoKICogUmV2aXNpb24gSGlzdG9yeQogKiAxMTEyMTkgR09TIChnZWlybXVuZHVyQHNreXJy
LmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAxMTEyMTkgR09TIFByaW1hcnkgdGVzdGlu
ZyBmaW5pc2hlZAogKgogKi8KCi8vIENvbnN0YW50cwpmaW5hbCBTdHJpbmcgVmFyTmFtZVBhdHRl
cm4gPSAiUGF0dGVybiI7CmZpbmFsIFN0cmluZyBWYXJOYW1lT2JqZWN0QXJyYXkgPSAiT2JqZWN0
QXJyYXkiOwpmaW5hbCBTdHJpbmcgVmFyTmFtZVJlc3VsdCA9ICJSZXN1bHQiOwoKLy8gSW5pdGlh
bGl6ZQpJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKaWYoaWRjID09IG51
bGwpCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkZhaWxlZCB0byBnZXQgQ3Vyc29yIHRv
IFBpcGVsaW5lIik7CgpTdHJpbmcgcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjLCBW
YXJOYW1lUGF0dGVybik7Ck9iamVjdFtdIG9iamVjdEFycmF5ID0gSURhdGFVdGlsLmdldE9iamVj
dEFycmF5KGlkYywgVmFyTmFtZU9iamVjdEFycmF5KTsKaWYocGF0dGVybiAhPSBudWxsKQp7CiAg
U3RyaW5nIHJlc3VsdDsKICBpZihvYmplY3RBcnJheSA9PSBudWxsKQogICAgcmVzdWx0ID0gcGF0
dGVybjsKICBlbHNlCiAgICByZXN1bHQgPSBqYXZhLnRleHQuTWVzc2FnZUZvcm1hdC5mb3JtYXQo
cGF0dGVybiwgb2JqZWN0QXJyYXkpOwogIElEYXRhVXRpbC5wdXQoaWRjLCBWYXJOYW1lUmVzdWx0
LCByZXN1bHQpOwp9CgovLyBDbGVhbiB1cAppZGMuZGVzdHJveSgpOwoKLyoKICogV2ViIE1ldGhv
ZHMgSmF2YSBNZXNzYWdlRm9ybWF0IEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==</value>
</Values>
