<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decryptString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CglieXRlW10ga2V5ID0gKGJ5dGVbXSkgSURhdGFVdGlsLmdldCggcGlwZWxpbmVDdXJz
b3IsICJjcnlwdEtleSIgKTsKCVN0cmluZwlpbnB1dFN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5wdXRTdHJpbmciICk7CglTdHJpbmcJY3J5cHRBbGdvcml0
aG0gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImNyeXB0QWxnb3JpdGht
IiApOwogICAgICAgIGlmIChjcnlwdEFsZ29yaXRobSA9PSBudWxsIHx8IGNyeXB0QWxnb3JpdGht
Lmxlbmd0aCgpPT0wKSB7CiAgICAgICAgICBjcnlwdEFsZ29yaXRobT0iREVTIjsKICAgICAgICB9
CQoJbXlDcnlwdCBvQ3J5cHQgPSBuZXcgbXlDcnlwdChrZXksY3J5cHRBbGdvcml0aG0pOwkJCglT
dHJpbmcgc0NyeXB0ZWRTdHJpbmcgPSBvQ3J5cHQuZGVjcnlwdEhleFN0cmluZyhpbnB1dFN0cmlu
Zyk7CgovLyBwaXBlbGluZQoKSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsImRlY3J5cHRl
ZFN0cmluZyIsc0NyeXB0ZWRTdHJpbmcpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CiA=</value>
</Values>
