<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">minus</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
W10gYSA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheSggcGlwZWxpbmVDdXJzb3IsICJhIiApOwpT
dHJpbmdbXSBiID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KCBwaXBlbGluZUN1cnNvciwgImIi
ICk7CgppZihhPT1udWxsKQp7CglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CQoJcmV0dXJuOwp9
CgppZihiPT1udWxsKQp7CglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgIm1pbnVzIiwg
YSApOwoJCglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CQoJcmV0dXJuOwp9CmphdmEudXRpbC5W
ZWN0b3IgdkFNaW5CID0gbmV3IGphdmEudXRpbC5WZWN0b3IoKTsKCmJvb2xlYW4gaW5CID0gZmFs
c2U7CmZvcihpbnQgY2E9MDsgY2E8YS5sZW5ndGg7IGNhKyspCnsKCWZvcihpbnQgY2I9MDsgY2I8
Yi5sZW5ndGg7IGNiKyspCgl7CgkJaWYoYVtjYV0uZXF1YWxzSWdub3JlQ2FzZShiW2NiXSkpCgkJ
ewoJCQlpbkI9dHJ1ZTsKCQkJYnJlYWs7CgkJfQoJfQoJaWYoIWluQikKCXsKCQlib29sZWFuIGlz
QWxyZWFkeUluUmVzdWx0ID0gZmFsc2U7CgkJZm9yKGludCBrPTA7IGs8dkFNaW5CLnNpemUoKTtr
KyspCgkJewoJCQlpZihhW2NhXS5lcXVhbHNJZ25vcmVDYXNlKChTdHJpbmcpdkFNaW5CLmdldChr
KSkpCgkJCXsKCQkJCWlzQWxyZWFkeUluUmVzdWx0ID10cnVlOwoJCQl9CgkJfQoJCWlmKCFpc0Fs
cmVhZHlJblJlc3VsdCkKCQl7CgkJCXZBTWluQi5hZGQoYVtjYV0pOwoJCX0KCX0KCWluQj1mYWxz
ZTsKfQoKCgppZih2QU1pbkIuc2l6ZSgpPjApCnsKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yLCAibWludXMiLCB2QU1pbkIudG9BcnJheShuZXcgU3RyaW5nWzFdKSApOwp9CnBpcGVsaW5l
Q3Vyc29yLmRlc3Ryb3koKTsK</value>
</Values>
