<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">IteratorHasNext</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBJ
dGVyYXRvckhhc05leHQgRmxvdwogKgogKiBqYXZhLnV0aWwuSXRlcmF0b3IgaGFzTmV4dCBtZXRo
b2QKICoKICogQ29weXJpZ2h0IFx1MDBBOSAyMDA5LCBLXHUwMEY2Z3VuIEx0ZCAod3d3LmtvZ3Vu
LmlzKS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4KICoKICogSW5wdXQ6IGphdmEudXRpbC5JdGVyYXRv
ciBJdGVyYXRvcgogKiBPdXRwdXQ6IFN0cmluZyBIYXNOZXh0ICgndHJ1ZScgb3IgbnVsbCkKICoK
ICogUmV2aXNpb24gSGlzdG9yeQogKiAwOTAzMTkgR09TIChnZWlybXVuZHVyQGtvZ3VuLmlzKSBD
cmVhdGVkCiAqCiAqIFVuaXQgdGVzdAogKiAwOTAzMTkgR09TIG5vdCBmaW5pc2hlZAogKgogKi8K
Ci8vIEluaXRpYWxpemUKSURhdGFDdXJzb3IgaWRjID0gR2V0QW5kQ2hlY2tDdXJzb3IocGlwZWxp
bmUpOwoKamF2YS51dGlsLkl0ZXJhdG9yIGl0ID0gRXh0cmFjdEl0ZXJhdG9yKGlkYywgZmFsc2Up
OwoKYm9vbGVhbiByZXN1bHQgPSBmYWxzZTsKaWYoaXQgIT0gbnVsbCkKICByZXN1bHQgPSBpdC5o
YXNOZXh0KCk7CgovLyBBZGQgdGhlIHJlc3VsdCB0byB0aGUgcGlwZWxpbmUKaWYocmVzdWx0KQog
IElEYXRhVXRpbC5wdXQoaWRjLCBIQVNfTkVYVCwgQm9vbGVhbi50b1N0cmluZyhyZXN1bHQpLnRv
TG93ZXJDYXNlKCkpOwoKLy8gQ2xlYW4gdXAKaWRjLmRlc3Ryb3koKTsKCi8qCiAqIFdlYiBNZXRo
b2RzIEphdmEgSXRlcmF0b3JIYXNOZXh0IEZsb3cgZW5kcwogKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovCg==
</value>
</Values>
