<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">PatternMatcher</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqCiAqIENvcHkgdGhpcyB0byB0aGUgV2ViIE1ldGhvZHMgSmF2YSBQ
YXR0ZXJuTWF0Y2hlciBGbG93CiAqCiAqIGphdmEudXRpbC5yZWdleC5QYXR0ZXJuIG1hdGNoZXIg
bWV0aG9kCiAqCiAqIENyZWF0ZXMgYSBtYXRjaGVyIHRoYXQgd2lsbCBtYXRjaCB0aGUgZ2l2ZW4g
aW5wdXQgYWdhaW5zdCB0aGlzIHBhdHRlcm4uCiAqCiAqIENvcHlyaWdodCAoYykgMjAxMSwgU2t5
cnIgTHRkICh3d3cuc2t5cnIuaXMpLiBBbGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBJbnB1dDog
IFBhdHRlcm4gICAgICAgKGphdmEudXRpbC5yZWdleC5QYXR0ZXJuKQogKiAgICAgICAgIElucHV0
ICAgICAgICAgKGphdmEubGFuZy5DaGFyU2VxdWVuY2UgLSBvcHRpb25hbCkKICogICAgICAgICBU
ZXh0ICAgICAgICAgIChTdHJpbmcgLSBvcHRpb25hbCkKICoKICogT3V0cHV0OiBNYXRjaGVyICAg
ICAgIChqYXZhLnV0aWwucmVnZXguTWF0Y2hlcikKICoKICogUmV2aXNpb24gSGlzdG9yeQogKiAx
MTA5MDkgR09TIChnZWlybXVuZHVyQHNreXJyLmlzKSBDcmVhdGVkCiAqCiAqIFVuaXQgdGVzdAog
KiAxMTA5MDkgR09TIEZpbmlzaGVkCiAqCiAqLwoKLy8gSW5pdGlhbGl6ZQpJRGF0YUN1cnNvciBp
ZGMgPSBHZXRBbmRDaGVja0N1cnNvcihwaXBlbGluZSk7CgpqYXZhLnV0aWwucmVnZXguUGF0dGVy
biBwYXR0ZXJuID0gRXh0cmFjdFBhdHRlcm4oaWRjLCBmYWxzZSk7CmphdmEubGFuZy5DaGFyU2Vx
dWVuY2UgaW5wdXQgPSBFeHRyYWN0Q2hhclNlcXVlbmNlKGlkYywgZmFsc2UpOwpTdHJpbmcgdGV4
dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjLCBURVhUKTsKCmlmKHBhdHRlcm4gIT0gbnVsbCkK
ewogIGlmKGlucHV0ID09IG51bGwpCiAgICBJRGF0YVV0aWwucHV0KGlkYywgTUFUQ0hFUiwgcGF0
dGVybi5tYXRjaGVyKHRleHQpKTsKICBlbHNlCiAgICBJRGF0YVV0aWwucHV0KGlkYywgTUFUQ0hF
UiwgcGF0dGVybi5tYXRjaGVyKGlucHV0KSk7Cn0KCi8vIENsZWFuIHVwCmlkYy5kZXN0cm95KCk7
CgovKgogKiBXZWIgTWV0aG9kcyBKYXZhIFBhdHRlcm5NYXRjaGVyIEZsb3cgZW5kcwogKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKiovCg==</value>
</Values>
