<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">updateItem</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCi8vIGxpc3QKSURhdGFbXQlsaXN0ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoIHBp
cGVsaW5lQ3Vyc29yLCAibGlzdCIgKTsKU3RyaW5nIHN0ckluZGV4ID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJpbmRleCIpOwoKSURhdGEgaXRlbSA9IElEYXRhVXRpbC5n
ZXRJRGF0YSggcGlwZWxpbmVDdXJzb3IsICJpdGVtIiApOzsKCnRyeSB7CiAgaW50IGluZGV4ID0g
SW50ZWdlci5wYXJzZUludChzdHJJbmRleCk7CgogIGxpc3RbaW5kZXhdID0gaXRlbTsKCn0KY2F0
Y2goTnVtYmVyRm9ybWF0RXhjZXB0aW9uIGUpIHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KGUuZ2V0TWVzc2FnZSgpKTsKfQoKSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJsaXN0
IiwgbGlzdCApOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
